### ISSUE TITLE
include data field to OptogeneticStimulusSite 

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/nwb-schema#101]
moved here from https://github.com/NeurodataWithoutBorders/pynwb/issues/311 by @BCJongbloets

> In case of laser scanning photostimulation (in and ex vivo) the location of the photostimulation ('OptogeneticStimulusSite' in 'ogen.py') is variable (XYZ and time). At the moment there is only the field 'Location' which allows for a string input. This suffices for a fixed stimulation location only.
> 
> To allow for description of variable locations it would be helpful to have a data field in class('OptogeneticStimulusSite' in 'ogen.py'). The data field should allow for storage of an 4 dimensional numpy array (XYZT).
> 
> Downside of this addition of the 'Data' field would be that users without variable locations need to provide a 'Data' array. I don't know if there is away to make the 'Data' field optional, hence I haven't made a version of 'ogen.py' myself?!

**Comment by mtv2101** [comment]
I fully support inclusion of arbitrary spatial and temporal stim parameters.  However, it lacks information about amplitude modulation and won't fully describe non-square-wave stimuli. Could it be changed to be (TXYZV, v=voltage) array?  Could this be parsed as either a singleton or as an array to accommodate both timestamps and space/time/voltage-varying coordinates?

**Comment by ajtritt** [comment]
@BCJongbloets I suggest you [extend](http://pynwb.readthedocs.io/en/latest/example.html#extending-nwb) OptogeneticStimulusSite to contain this information. You could also extend [TimeSeries](http://pynwb.readthedocs.io/en/latest/overview.html#timeseries) depending on how you view this type of data.

**Comment by campagnola** [comment]
I agree this is important enough to (eventually) include in the core specification. To expand on @mtv2101's comment, though, photostimulation parameters can come in many different forms:

* Is power a square pulse, a train of pulses, or an arbtrary waveform?
* Is the stimulus a single spot, multiple spots, or an arbitrary shape?
* Does the spot position or shape change over time (such as with spiral/raster scanning, or with a rapidly updating SLM image)?

It's probably not necessary for the spec to account for all of these possibilities (at least not yet), but it would be very helpful to have a minimal set of common features supported.

**Comment by rly** [comment]
We will revisit this and form an optogenetics working group when there is greater demand from users.
