### ISSUE TITLE
input validation functions

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#105]
Would it be possible to have the option of including additional input validation functions for new types in NWB extensions?

**Comment by ajtritt** [comment]
What kind of validation do you want to do? PyNWB already has some functionality for validating with extensions.

**Comment by bendichter** [comment]
I may be doing this wrong, but I am not finding datatype checks. I am specifying a Surface datatype like so:
```python
from pynwb.spec import NWBDatasetSpec, NWBNamespaceBuilder
from pynwb import get_class, load_namespaces

ns_path = "img_pipe.namespace.yaml"
ext_source = "img_pipe.extensions.yaml"

surface = NWBDatasetSpec(doc='brain cortical surface',
                         neurodata_type_def='Surface',
                         dtype=[{'dtype': 'int',
                                 'name': 'faces',
                                 'doc': 'triplet sets of vertices that make each face'},
                                {'dtype': 'float',
                                 'name': 'vertices',
                                 'doc': 'spatial location of each vertex'}])

ns_builder = NWBNamespaceBuilder('img_pipe extensions', "img_pipe")

for spec in [surface]:
    ns_builder.add_spec(ext_source, spec)

ns_builder.export(ns_path)
```

and then when I try to use it:
```python
load_namespaces(ns_path)
Surface = get_class('Surface', 'img_pipe')
aa = Surface(data={'faces':['a', 1, 2], 'vertices':[3, 4, 5]})
```
there doesn't appear to be a check that `'faces'` is of type `'int'` at this point. The code executes without error.

I'd also like to do things that aren't likely to be supported already. I am working right now on extending to support a surface dataset, which includes `faces` and `vertices`. One thing I'd like to do is include a check that they are compatible, e.g. the indices referenced by the `faces` dataset don't exceed the size of `vertices`.

**Comment by ajtritt** [comment]
@bendichter can we close this? I think we solved the Surface extension, right?
