### ISSUE TITLE
Update GitHub project description

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/nwb-schema#109]
Text could be `A schema definition for storing neurodata in HDF5 format.`

![screenshot from 2018-01-20 14-29-36](https://user-images.githubusercontent.com/219043/35187229-7bb19b66-fdee-11e7-94ef-2ed0f94d032e.png)

**Comment by nicain** [comment]
And a link to the nwb.org website.

**Comment by neuromusic** [comment]
duplicate of #98

**Comment by jcfr** [comment]
Closing. This issue is a duplicate
