### ISSUE TITLE
add `noise_num` and `multiunit_num` to Clustering

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#111]
I'd like to add two variables to `Clustering`, `noise_num` and `multiunit_num`. These values would be `None` by default, but could be assigned integer values up to the number of unique clusters in the give `Clustering` object. These values would indicate to a recipient if some of the clusters were not thought to be reflecting a specific neuron's action potential. Leaving the arguments as `None` would indicate that all clusters are thought to be reflecting a specific neuron's action potential.

Currently, the user is instructed to give this information in text form, but I think these designations are common enough in clustered data that it would be useful to have a way to represent this information programatically

**Comment by tjd2002** [comment]
@bendichter Can this be closed now that per-cluster metadata is stored in the Units table?
