### ISSUE TITLE
Restructure ROI storage to make more efficient

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/nwb-schema#118]
# Problem
Right now ROIs are stored as a single group per ROI. This structure is inefficient for storing large numbers of ROIs. RoiResponseSeries' relationship to ROI objects is implicit (i.e. ROI is specified by a string), so must know a priori which ImageSegmentation and ImagingPlane was used to produce the ROIs.  

# Proposal
To make ROI storage more efficient and explicit,  we would like to make the following changes:

1. Replace ROI.img_mask with a 3D dataset with shape [num_rois, num_x_pixels, num_y_pixels] (i.e. an array of image masks)
2. Replace ROI.pix_mask/ROI.pix_mask_weight with a table that has columns “x”, “y”, and “weight” (i.e. ROI.pix_mask and ROI.pix_mask_weight into a single table)
3. Add an ROI table with columns "id", "description", "img_mask_ref", and "pix_mask_ref"
        - "id" holds a unique identifier for each ROI
        - "description" stores a description for each ROI
        - "img_mask_ref" stores a region reference into the img_mask dataset (described above in 1.)
        - "pix_mask_ref" stores a region reference into the pix_mask/pix_mask_weight dataset (described above in 2.)
4. RoiResponseSeries.roi_names gets replaced with RoiResponseSeries.rois, a scalar dataset that stores a region reference into the ROI table (described above in 3.)
5. Remove RoiResponseSeries.segmentation_interface. This information will be available through RoiResponseSeries.rois (described above in 4.)

**Comment by oruebel** [comment]
@ajtritt this looks good to me.

**Comment by jonc125** [comment]
With AOL microscopy (#156) an ROI can be a 3d volume, and hence we'd need the img_mask & pix_mask to allow an optional z coordinate. Could this be added?

See also #60 which suggests removing redundancy by only storing one of pix_mask & img_mask.

**Comment by jonc125** [comment]
Another query: does this approach force all ROIs to have the same dimensions? This will eventually cause problems for us, as we'll have varying sized ROIs next year most likely.
