### ISSUE TITLE
Restructure Epoch storage to make more efficient

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/nwb-schema#119]
# Problem

Right now Epochs are stored as a single group per Epoch. Within each Epoch, the index into each TimeSeries that the Epoch applies to is stored as a single group. This structure is inefficient for storing large numbers of Epochs. 

# Proposal

To make Epoch storage more efficient, we would like to make the following changes:

1) Replace the Epoch type with the new type EpochTable, a table with the following columns:
        - _start_ - the start time of each Epoch
        - _stop_ - the stop time of each Epoch
        - _description_ - a description for each Epoch
        - _tags_ - tags describing each Epoch
        - _ts_ref_ - a region reference into the TimeSeriesIndex (described below) for the TimeSeries indexed for each Epoch

2) Replace EpochTimeSeries with the new type TimeSeriesIndex table, a table with the following columns:
        - _start_idx_ - the start index in the TimeSeries
        - _count_ - the number of time points in the TimeSeries
        - _timeseries_ - an object reference to the TimeSeries object

**Comment by bendichter** [comment]
@ajtritt Looks good to me!

**Comment by oruebel** [comment]
@ajtritt this looks good to me too.

**Comment by ajtritt** [comment]
@bendichter @oruebel I updated the proposal. No structural changes, just changed the name of the second table. This naming is meant to imply that this structure can be used elsewhere, not just for epochs.

**Comment by oruebel** [comment]
@ajtritt looks good

**Comment by jonc125** [comment]
I like this new approach much better than the original. It'll make our lives generating NWB simpler, certainly.

Presumably this (and #118) mean the old way of storing these will no longer be supported in new NWB 2 files, and so conversion will be required for existing data? Will PyNWB provide such conversion?

**Comment by ajtritt** [comment]
A conversion tool is unlikely. There are a lot of technical hurdles to a 1-to-2 conversion tool, including this issue, #118, and the ambiguous "Custom" neurodata_type from 1.0.

We are prioritizing documentation, examples and tutorials for PyNWB with the intention of empowering users to build their own conversion tools.

**Comment by oruebel** [comment]
> We are prioritizing documentation, examples and tutorials for PyNWB with the intention of empowering users to build their own conversion tools.

Agreed.

There is some legacy read support for the Allen Brain Atlas data which uses 1.0.x, however, in general we can't make backwards compatibility guarantees for 1.0x in general. In addition to the items @ajtritt  mentioned, another part of the problem is also that at least of the original files I have seen, none were actually fully compliant with the standard, e.g., required data is missing, custom fields are being added without a spec etc., i.e., many of the files are really more 1.0.x-like. This makes supporting 1.0.x at large very challenging. With the new architecture of NWB 2.0 I think we are in a much better position to make compatibility happen going forward.

**Comment by jonc125** [comment]
That makes sense. Fortunately we can generate NWB2 fresh from the raw data, so don't need to convert. But it sounds like I'd better target this new ROI structure rather than the SfN version!

**Comment by t-b** [comment]
@oruebel 

[...]
"none were actually fully compliant with the standard, e.g., required data is missing, custom fields are being added without a spec".

I would say that adding custom fields without a spec is standards compliant.

The NWB v1 spec says under "Extending the format":

```
There are two ways to document these additions. The first is to add an attribute
"neurodata_type" with value the string "Custom" to the additional groups or datasets, and
provide documentation to describe the extra data if it is not clear from the context what the data
represent.
```

**Comment by oruebel** [comment]
@t-b yes that's true for NWB 1.0.x. Note that ``custom`` has been removed in NWB 2, i.e., to add custom data you should now always create an extension. Supporting arbitrary fields without a formal spec is a very deep hole and supporting all possible custom data cases in a usable way is near impossible.

**Comment by t-b** [comment]
@oruebel Thanks. Although this makes porting my application to v2 more work I think this is a good step.
