### ISSUE TITLE
Update spec of shape for OpticalSeries.field_of_view in nwb.image.yaml

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/nwb-schema#12]
Originally reported by: **Oliver Ruebel (Bitbucket: [oruebel](https://bitbucket.org/oruebel), GitHub: [oruebel](https://github.com/oruebel))**

----------------------------------------

The current specification of OpticalSeries.field_of_view is

- dims:
  - - width|height
    - width|height|depth
  doc: Width, height and depto of image, or imaged area (meters).
  dtype: float32
  name: field_of_view
  quantity: '?'
  shape:
  - 2

For the shape to be consistent with the dims, the shape should change to:

shape: 
  - - 2
    - 3

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/nwb-schema/issue/12

**Comment by oruebel** [comment]
@ajtritt has this fix made it into the schema in PyNWB?
