### ISSUE TITLE
Stimulus metadata

### ISSUE THREAD

**Issue by campagnola** [NeurodataWithoutBorders/nwb-schema#131]
In many of our experiments, it is necessary to track the parameters of complex stimuli that are presented. The diversity of these parameters across the many different types of experiment presents a data management challenge: how do we allow a description of stimuli that is (1) standardized enough to allow similar experiments to share processing tools, and (2) flexible enough to accommodate most types of experiment?

**Examples**

* Intracellular stimuli in patch clamp experiments (pulses, pulse trains, ramps, noise, etc.)
* Extracellular electrical stimulation (https://github.com/NeurodataWithoutBorders/nwb-schema/issues/130)
* Optogenetic stimulation (https://github.com/NeurodataWithoutBorders/nwb-schema/issues/101) with spatial information
* Sensory stimuli (visual, auditory, etc)

**Representation of stimuli** (templates, presentations, metadata)

What is the best way to represent stimuli? I can think of a few possibilities:

1. Time-series waveforms describing each stimulus presentation. This is the most "raw" approach, and the least prone to acquisition error. It also requires the most storage, and is probably the most prone to analysis error--determining the contents of the stimulus requires manually analyzing the waveform to deduce the intended structure.
2. Time-series templates containing the waveform of a stimulus that may be applied multiple times during the experiment. These have the advantages that (1) repeated stimuli are only stored once, and (2) it becomes easier to group together presentations that all used the same template, without having to compare their stimulus waveforms.
3. Metadata describing each stimulus presentation. For example, a pulse train might look like:
    ```
    start_time: 1.35s
    pulse_width: 10ms
    interpulse_interval: 30ms
    amplitude: 50µV
    pulse_count: 20
    ```
    This approach is compact and easiest to search / analyze--we can directly sort through responses based on some feature of the stimulus. The downside is that the actual stimulus waveform is non-trivial to reconstruct from here.
4. Metadata templates: combined benefits from (2) and (3).

I think the schema we come up with should support all of these options simultaneously. For example, I would prefer to be able to store both metadata (3) and the per-presentation stimulus waveform (1) in my experiments.

**Implementation of stimulus schema** (inheritance vs composition)

NWB encourages the use of subclassing in the schema to implement new metadata structures. However, the diversity and complexity of these stimuli may be difficult to represent using this approach.

As an example of the problem to be solved, imagine a typical current-clamp recording in which a single square pulse stimulus is applied to the cell. This stimulus has a few properties: `start_time`, `amplitude`, and `duration`. One way to describe this is to create a schema extension with a class called CurrentClampPulseSeries that extends currentClampStimulusSeries and adds the three properties listed above.

The problem with this approach is that it is not straightforward to describe an experiment with two (or more) different stimuli in a single sweep. For example, a sweep that has a square pulse followed by a ramp. Ideally this should be solvable by composing the stimulus information together (like: "stimulus _has_ a pulse and a ramp") rather than by creating an entirely new class to describe this specific combination (like: "stimulus _is_ a pulse plus a ramp"). In other words we want to use composition rather than inheritance (this topic is extensively discussed on the web, for example https://en.wikipedia.org/wiki/Composition_over_inheritance). This problem is further exacerbated by the multiple base classes that might want to include these stimuli--a simple pulse stimulus, for example, might create new classes inheriting from CurrentClampStimulusSeries, VoltageClampStimulusSeries, OptogeneticStimulusSeries, ExtracellularStimulusSerries, etc.

**Comment by oruebel** [comment]
@campagnola I don't think the schema language favors inheritance over composition. Some of the neurodata_types in the current schema may do this, but the schema language does not prevent you from composing types. To add a type to another type you simply use the ``neurodata_type_inc`` key in the specification language. Ultimately that is how types are being reused in the format spec. Just a random example, here a snippet of the spec of BehaviorialEpochs:

```
groups:
- doc: IntervalSeries object containing start and stop times of epochs
  neurodata_type_inc: IntervalSeries
  quantity: '*'
neurodata_type_def: BehavioralEpochs
neurodata_type_inc: NWBContainer
```

This creates a new type ``BehavioralEpochs`` that inherits from ``NWBContainer`` and contains (i.e., is being composed of) zero or more ``IntervalSeries``. 

In that vain, you could, e.g., have a type ``Stimulus`` that is being composed of one or more``StimulusComponent`` objects. The trick then becomes to identify the kind of components that a Stimulus is being composed of.

**Comment by oruebel** [comment]
#130

**Comment by bendichter** [comment]
Could we separate out discussion of manipulations [e.g. intracellular stimulation, extracellular stimulation, optogenetic, magnetic, cooling etc.] from sensory stimuli [audio, visual, olfactory, presentation, etc.]?

There are number of differences between these types of experimental procedures and I think trying to find a common specification that can accommodate both simultaneously will only get in our way. This discussion of pulse features is relevant to most manipulations, but would rarely be relevant for sensory stimuli. While it is certainly true that manipulations are sometimes used like an additional sensation, they are also commonly used in a more pharmaceutical manner to activate or deactivate a region or population. Most manipulations will be associated with electrodes/fibers/devices, while this may not be necessary for some sensory stimuli. Sensory stimuli may not repeat, in which case (2) and (3) would not be appropriate, whereas they might be our best bet for manipulations. Sensory stimulations will often be exactly the same between sessions, so linking to an external NWB file might be necessary to prevent unnecessary duplication of data, especially for video files, which can be very large.

We should discuss both, I just don't want them to be clumped together.

As for the enumerated options for describing manipulations, I think that list is a great breakdown of the options, and I can see use-cases for each. In cases where a manipulation is meant to mimic some sense or is white noise, it may not repeat, so (2-4) are not appropriate and (1) must be used. If the stimulus repeats, but is an unusual shape that is hard to parameterize, (2) would likely be best. If it's a common shape, like a mono or biphasic pulse (3 or 4) would probably be ideal.

**Comment by campagnola** [comment]
I am open to the idea of separating these, but my sense is that we will be able to accommodate all types of stimuli with the same basic framework (and that we will be better off by doing so), beginning with @oruebel's suggestion above. Let's dig into this a bit further and decide later whether they really are completely distinct ideas? For motivation, here is an example @neuromusic posted elsewhere:

> NWB does not distinguish between a sensory stimulus & a electrical stimuluation. Both are captured using the stuff in "stimulus", so any changes made for intracellular electrical stimulation will affect sensory stimulus representations, as well.
>
> Fortunately, in the sensory stimulus domain, we have similar needs. I'm pretty sure #1 and #2 are both covered in the current design, but #3 is not and would be very useful.
>
> For example, if I'm presenting MNIST digits in an experiment, I want to capture both the image that was used as well as "intrinsic" metadata (e.g. the digit category and the identifier), operational metadata (where the image was placed and sized on the screen), and perhaps computed metadata (summary statistics of the image).

It would probably help for us to start by collecting a list of use cases. I'll offer a few below..

**Comment by campagnola** [comment]
**Example use cases:**

* **Locally sparse noise (visual stimulus)**: like http://observatory.brain-map.org/visualcoding/stimulus/locally_sparse_noise. This is a complex stimulus that may or may not repeat; very likely modes 1 and/or 2 will be used, and the stimulus data consists of a 3D array. However, there is a lot of information we may need about the stimulus that is not captured by the image data alone. I might want something like:
    ```
    name: 'locally sparse noise 4 deg'
    image_data: [link to template or presentation dataset]
    start_time: ...
    duration: 30s
    frame_interval: 250ms
    display_device: 'screen1'
    origin: (x, y)
    scale: (w, h)
    pixel_size: 4.65deg
    exclusion_zone: 5px
    on_density: 0.02
    on_value: 0.9
    off_density: 0.02
    off_value: 0.0
    background_value: 0.5
    random_seed: 12345
    ```

* **Locally sparse noise (photostimulation)**: very similar to the previous example, but using an SLM rather than a screen to rapidly photostimulate different regions of tissue. 

* **Pup calls (auditory stimulus)** A recording of pup calls played back; metadata might look like:
    ```
    name: "pup call"
    wave_data: [link to template or presentation dataset]
    playback_device: "open-field left speaker"
    start_time: ...
    duration: 3.5s
    scale_factor: 0.7
    dBSPL: 75
    filters: [list of filters applied]
    ```

* **Tone pip (auditory stimulus)** 
    ```
    name: "tone pip"
    wave_data: [optional link to template/presentation dataset]
    playback_device: "closed field speaker left"
    start_time: ...
    duration:  250ms
    ramp_duration: 20ms
    f0: 12kHz
    amplitude: 0.5
    dBSPL: 80
    ```  

* **Sinewave current injection (patch clamp)*** : very similar to auditory stimulus above, but providing current injected into a patch clamp electrode.

**Comment by joeyo** [comment]
1. and 2. are ready as-is (at least as I understand the current state of NWB) --- they would need a link to an electrode group, but would otherwise be perfect for a variety of brain stim (intracortical, macro, TMS, tACS, etc).

3. Sounds appealing; could the metadata simply be a list of keys and values, where it's up to the experimenter to define a set of meaningful keys? Or is there a desire to enumerate a bunch of well-known features in the spec? My concern is that there will be a combinatorial explosion if NWB goes down the latter path.

**Comment by campagnola** [comment]
@joeyo can you elaborate on "combinatorial explosion", perhaps with an example?

**Comment by oruebel** [comment]
> Sounds appealing; could the metadata simply be a list of keys and values, where it's up to the experimenter to define a set of meaningful keys?

If you leave this all up to the user then that defeats in many ways the purpose of a standard. However, I agree that users will likely want to be able to add additional data (either via extensions or by providing a generic container for StimulusComponents that users can populate). For this sort of complex metadata we'd ideally have the ability to link to other ontologies that define what valid keys/values are, rather than coding all of this in the schema. While support for ontologies is a known need and is part of the future road map, this will take some time and will most certainly not be available in NWB 2.0 yet. What I would suggest is to come up with the most common things and to make sure that the structure can be easily extended. Allowing this through composition like @campagnola  suggested seems like a reasonable idea.

**Comment by orubel** [comment]
whil I am a software developer and an original team member of Amazon, I
think you have the wrong 'orubel' :)

Owen Rubel
orubel@gmail.com

**Comment by oruebel** [comment]
@orubel sorry for the noise. That was for me @oruebel, but nice to meet you :-)

**Comment by orubel** [comment]
Good to meet you to. I suspect we are related somehow; all rubels/ruebels
are. :)

Owen Rubel
orubel@gmail.com

**Comment by campagnola** [comment]
After some long discussions this week, we came to the proposal in #141 as a way to solve the inheritance vs composition problem I referenced at the top of the page. This has two implications for the current issue:
1. We should wait for #141 to be nailed down before putting too much effort into this issue
2. @bendichter may get his wish to separate discussion of the various types of stimuli--because #141 seeks to solve the composition problem at a lower level, it is no longer necessary for each of the stimulus-metadata cases to piggyback off of the solution chosen here.

**Comment by bendichter** [comment]
I do like getting my wish but in light of the convo today I understand the motivation for a unified scheme now. Some kind of compromise may be ideal. Thanks for all the hard work and patience today.

**Comment by rly** [comment]
@lydiang you may be interested in this for your stimulus ontologies.

**Comment by orubel** [comment]
again... wrong orubel. People really need to learn to spell our names right.

Owen Rubel
orubel@gmail.com

**Comment by rly** [comment]
@orubel Sorry, Owen. You were notified because you were accidentally tagged earlier. Unfortunately, I cannot unsubscribe you AFAIK. Please unsubscribe to this issue in the right column of the issue page on GitHub.

**Comment by bendichter** [comment]
@satra also see this old convo about formal stimulus description

**Comment by oruebel** [comment]
Closing the issue as this is being addressed by the following INCF working group https://www.incf.org/sig/incf-working-group-electrophysiology-stimulation-ontology and as such will be part of a future extension proposal.
