### ISSUE TITLE
Change `ophys.ImagingPlane` fields `excitation_lambda` and `imaging_rate` from `str` to `float`

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#136]
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/a0042022f7cf1dc0c7a6a17bbfa17fc5c5e41824/core/nwb.ophys.yaml#L197

Is there a reason why these are stored as strings? It seems more sensible to store them as floats.

**Comment by ajtritt** [comment]
This got carried over from 1.x, but I agree, a float or a double would make more sense.

**Comment by elyall** [comment]
Also in all other classes, the sampling rate parameter is referred to as "rate". So I'd suggest changing the parameter's name ("imaging_rate" -> "rate") and the data type (str -> float).

**Comment by elyall** [comment]
Alternatively, ImagingPlane's sampling rate parameter is redundant and can be removed altogether since all Series data tied to an ImagingPlane have to have their own rate/timestamps specified.

**Comment by bendichter** [comment]
@oruebel @ajtritt how do you guys feel about removing imaging_rate from ImagingPlane as @elyall suggests? Might that cause issues I am not seeing?

**Comment by oruebel** [comment]
This is fixed in https://github.com/NeurodataWithoutBorders/pynwb/pull/612
