### ISSUE TITLE
Alphabetical key order makes yaml files difficult to read

### ISSUE THREAD

**Issue by campagnola** [NeurodataWithoutBorders/nwb-schema#139]
As an example, the `ImageSeries` definition in `nwb.image.yaml` orders its top-level keys like `attributes, datasets, doc, neurodata_type_def, neurodata_type_inc`, whereas having `neurodata_type_def` show up first would be much more natural and readable.

It should be trivial to fix this, assuming it doesn't break anything else. The following script generates nice output:
```python
import sys
from ruamel import yaml
import collections

order = ['neurodata_type_def', 'neurodata_type_inc', 'name', 'dtype', 'doc']
def sort_keys(obj):
    if isinstance(obj, dict):
        keys = list(obj.keys())
        for k in order[::-1]:
            if k in keys:
                keys.remove(k)
                keys.insert(0, k)
        return yaml.comments.CommentedMap(yaml.compat.ordereddict([(k,sort_keys(obj[k])) for k in keys]))
    elif isinstance(obj, list):
        return [sort_keys(v) for v in obj]
    elif isinstance(obj, tuple):
        return (sort_keys(v) for v in obj)
    else:
        return obj

data = yaml.load(open(sys.argv[1], 'rb'), Loader=yaml.RoundTripLoader)
sorted = sort_keys(data)
print(yaml.dump(sorted, Dumper=yaml.RoundTripDumper))
```

**Comment by bendichter** [comment]
Thanks for this @campagnola. We agree that the order you propose would make the yaml files more readable. I think addressing this properly will involve:

1) Applying this script to each of the spec files
2) Set this script up to apply automatically to generated extensions

Anything else? I like the idea of facilitating this ordering but I don't think we should enforce it.

**Comment by oruebel** [comment]
> I don't think we should enforce it

I agree, there should not be need to enforce this. This is mainly for human-readability but we should not make assumptions about the ordering the code. 

> Set this script up to apply automatically ...

I think we really just need to update the output in spec writer functions of PyNWB to sort the keys on output accordingly.

**Comment by bendichter** [comment]
Thanks @campagnola! This fix was a breeze with your code.
