### ISSUE TITLE
Missing neurodata_type Image

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#143]
# Bug

The neurodata_type ``Image`` is used as part of ``Images`` but does not seem to be defined. The following code from nwb.base.yaml:

```
...
197   datasets:
198     - doc: Images stored in this NWBDataInterface
199       neurodata_type_inc: Image
200       quantity: '+'
...
203   neurodata_type_def: Images
...
```

We probably need to update the ``Images`` type to replace ``Image``. Also should ``Images`` be moved to nwb.image.yaml?

**Comment by oruebel** [comment]
```
git diff ad81efbadfe580fb73aee499248736f468b2d0bb~ ad81efbadfe580fb73aee499248736f468b2d0bb
[...]
202 @@ -45,32 +45,9 @@ groups:
203        group, the data can exist in a separate HDF5 file that is linked to by the file
204        being used for processing and analysis.'
205      groups:
206 -    - datasets:
207 -      - attributes:
208 -        - doc: 'Human description of image. COMMENT: If image is of slice data, include
209 -            slice thickness and orientation, and reference to appropriate entry in
210 -            /general/slices'
211 -          dtype: text
212 -          name: description
213 -        - doc: 'Format of the image.  COMMENT: eg, jpg, png, mpeg'
214 -          dtype: text
215 -          name: format
216 -        doc: 'Photograph of experiment or experimental setup (video also OK). COMMENT:
217 -          Name is arbitrary.  Data is stored as a single binary object (HDF5 opaque
218 -          type).'
219 -        dtype: binary
220 -        neurodata_type_def: Image
221 -        quantity: '*'
[...]
```

**TODO**:
* Add Picture  as a dataset base type to nwb.base.yaml. 
    * See spec for Image above, just rename to Picture and add a ``shape: -null`` to indicate a 1D shape
* Add GrayScaleImage dataset type that is a simple 2D array of floats (``shape: - null -null``)
* Add ColorSpaceImage dataset type that is 3D array of floats (``shape: -null -null -null``) where the third dimension is the color space (e.g., RGBA). 
* Update the Images type to allow for Picture, GrayScaleImage or ColorSpaceImage

**Comment by bendichter** [comment]
@oruebel It looks like [`dtype: binary` is no longer supported](https://schema-language.readthedocs.io/en/latest/specification_language_description.html#dtype). Should we add this to the supported data types?  I'm not clear on what `Picture` would provide. Is the idea so we can support lossy image formats like jpeg?

`uint8` and `uint16` are pretty standard for images. In either case the intensity values are mapped onto the full range of values. If we use `float`, we should specify the range. It's [common practice](http://scikit-image.org/docs/dev/user_guide/data_types.html) to use 0 to 1 or -1 to 1.

A potential alternative to adding 3 new dataset types would be to use the shape of the image to define the type of image i.e.:

2D: grayscale image
3D:
    - x,y,3: RGB
    - x,y,4: RGBA

but I don't see much of an advantage one way or another. If we do define a dataset type for each kind of image, do we want a base `Image` class that holds common features like `resolution`?

**Comment by ajtritt** [comment]
> A potential alternative to adding 3 new dataset types would be to use the shape of the image to define the type of image i.e:

We want to avoid encoding special meaning in values of schema directives. Type should be explicit, not an implicit property determined by a property of the data.
