### ISSUE TITLE
sex ≠ gender

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#146]
from the schema:

```
- doc: Gender of subject
  dtype: text
  name: sex
```
I imagine this would only ever come up for human subjects, but in the interest of being socially conscious we should decide if we are asking for gender or sex. Possibly we should have sex and then an additional optional field for "gender (if different from sex)." I've seen this distinction come up in some journal and funding agency guidelines, so it's a distinction that is likely to come up for users

**Comment by tjd2002** [comment]
Certainly for animal data, we want to refer to 'Sex' not 'Gender'.

Not sure what best practices are for human subjects data.

**Comment by tgbugs** [comment]
https://cde.nlm.nih.gov/cde/search?q=gender gives one perspective. There are probably a whole bunch of different operational definitions ranging from ones that are identical to `sex` all the way through a free text `self reported gender` which the schema won't know about ahead of time.
