### ISSUE TITLE
add behavior.Orientation

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#150]
@DavidTingley

**Comment by DavidTingley** [comment]
I believe there is a need for a behavior.orientation class.  Our current behavior tracking system outputs position (x/y/y), head orientation (pitch/yaw/roll in euler or x/y/z/w in quaternion coordinates), and error per marker (Nx1 estimation of position error per frame).

A more general VectorSeries could be used to encapsulate .Position, .Orientation, and .Error (and other measurements). 

This may become especially crucial as more complex behavior tracking systems get adopted (tracking multiple animals, different body parts, etc).

**Comment by rly** [comment]
Closing in favor of `CompassDirection` type
