### ISSUE TITLE
"conversion" in create_imaging_plane

### ISSUE THREAD

**Issue by sebiRolotti** [NeurodataWithoutBorders/nwb-schema#151]
It looks like the conversion parameter here takes a float - this makes a strong assumption that the microns-per-pixel is equal for x and y. This should actually be a tuple? We could then potentially allow users to pass a single float for cases in which x and y sizes are the same.

Maybe I should open up a different issue, but this leads to a related problem for z. Its not totally clear to me how to handle multi-plane imaging data. I can slice up my dataset and have a different imagingPlane (and TwoPhotonSeries) for each plane, but we would then need to have some way of storing the z spacing (in microns or whatever the unit is) between each plane.

**Comment by bendichter** [comment]
I think the `manifold` parameter is meant to deal with this but I don't think the structure of that is ideal either. Are there ever irregular spatial grids? i.e. dx, dy, and dz aren't consistent between neighboring pixels? If grids are always regular, all was need is (dx, dy, dz) and maybe (x0, y0, z0)

**Comment by sebiRolotti** [comment]
I can't think of any use cases where you would have a spatial grid that is irregular, but I could be wrong. Agreed that all we should really need is (dx, dy, dz).

I also agree the manifold parameter doesn't seem to be an ideal structure (addressed in #59), but in any case this seems to be more applicable to cases where you don't have a grid (or even an image plane) per se (i.e., random-access microscopy).

**Comment by jonc125** [comment]
Indeed, this is important for [acousto-optic lens microscopy](https://www.nature.com/articles/nmeth.4033#methods) where the manifold is potentially an arbitrary collection of pixels. We managed to get our data stored using the 1.x schema; I still need to work on updates for version 2. It's additionally complicated by the fact that you're directly acquiring what in traditional microscopy would be an ROI response series. I'll try to write up further notes on what we've done thus far later today, for discussion.

**Comment by bendichter** [comment]
thanks @jonc125 that sounds really helpful. In your notes could you please be explicit about what specific information would be necessary to specify the pixel locations for this type of microscopy?

**Comment by jonc125** [comment]
Didn't manage to finish this yesterday, but I've now added some thoughts in #156 as it touches on much more than just this issue. I'll think further next week about whether additional changes to the schema might be needed.

**Comment by rly** [comment]
We have restricted imaging planes to be a regular grid for the time being. Please see #305. However, we can support non-regular imaging planes through an extension as necessary.
