### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/nwb-schema#153]
I removed branches already merged and `master` branch which was both not used and also a subset of `dev`.

Three branches are remaining:

![image](https://user-images.githubusercontent.com/219043/39392591-73bb0d72-4a86-11e8-8a4f-26fb1eb03c30.png)

@oruebel @ajtritt I think we should either remove these branches or update them.

**Comment by t-b** [comment]
@jcfr I would suggest that everyone works in his own fork so only public branches (release branches, etc. are present here.

**Comment by oruebel** [comment]
@jcfr I updated and merged the ``update_release_notes`` branch. This was a branch I used to catch up on release note changes and forgot about. It looks like ``hotfix`` and ``recommended_fix`` don't have any changes on them so they can probably be deleted, but I think those two are from @ajtritt

**Comment by jcfr** [comment]
Thanks for looking into this.

> It looks like hotfix and recommended_fix don't have any changes on them so they can probably be deleted

@ajtritt  Any objections if we remove these branches ?
