### ISSUE TITLE
Thoughts for supporting acousto-optic lens microscopy

### ISSUE THREAD

**Issue by jonc125** [NeurodataWithoutBorders/nwb-schema#156]
This style of microscopy can rapidly acquire arbitrary pixels within a spatial volume. Following an initial traditional single acquisition of the whole volume (the reference Z stack), regions of interest are defined in the control software, and then just these ROIs are acquired over the course of the experiment. ROI timeseries data is thus acquired directly, rather than being determined in post-processing.

ROIs can take various shapes:
1. Multi-volume acquisition: acquire one or more smaller cuboids within the overall region. At present all cuboids have the same dimensions, but easing this restriction is planned. (There's also a chance they won't need to be cuboids.)
2. Often these cuboids have height 1 as a special case.
3. Line scanning: acquiring one or more straight-line segments having any orientation within the overall region. At present all segments are of the same length, but this will change next year. (In a more distant future, curved lines should be supported.)
4. Single voxel acquisition: each ROI is a single point located anywhere within the overall region.

Our approach with NWB1:
- The reference Z stack is stored as single-time `TwoPhotonSeries` in `/acquisition/timeseries/Zstack_<channel>_<plane>`.
- ROI data is stored within a `TwoPhotonSeries` for each channel for each ROI in `/acquisition/timeseries`.
- We store an extra dataset giving pixel acquisition time offsets, since we can calculate when each pixel in an ROI was acquired relative to when the ROI as a whole started being acquired, which is what is stored in the `timestamps` dataset.
- Only the cases (2) and (4) above have been implemented so far. For these we can define the ROI locations related to the planes of the reference Z stack, since each ROI lies completely within a single horizontal plane. The relevant plane from the Z stack is used as the reference image.
- Within an `ImageSegmentation` we group the ROIs by Z coordinate, since each imaging plane should only be listed once in the `ImageSegmentation` module; within a given plane, the original relative ordering of ROIs is maintained.
- We do make use of the `manifold` dataset (cf #59) to record the actual physical dimensions of the reference Z stack, and hence (via the segmentation) the coordinates of the ROIs can in principle be retrieved.

Related issues: #151 #118 #59 #60 #103 #158

Thoughts welcome about whether the changes proposed in these issues will make life easier for us, and mean we can support all ROI shapes naturally. I'll try to have a proper think about it next week too!

Related links:
* [Paper about the experimental setup](https://www.nature.com/articles/nmeth.4033#methods)
* [Our prototype code importing data to NWB1](https://github.com/SilverLabUCL/SilverLab_NWBv1)

**Comment by jonc125** [comment]
AOL use cases (1) and (3) cannot be represented in NWB1 (or the present NWB2 draft) since the mask is always 2d (even though an ImageSeries can be 3d+t). I've noted what needs changing to fix this in #118 and #59.

Along with the other changes already proposed, I think those would enable us to represent all our *current* imaging data.

**Comment by bendichter** [comment]
Hey Jon, thanks this in-depth description is very helpful. It's been on the back-burner a bit, and probably will continue to be until the 2.0 release, but we really appreciate the help and this will definitely be incredibly useful once we get through some high priority compatibility issues.

**Comment by jonc125** [comment]
Thanks for the update Ben. We're going to have a sprint here in July porting our code over to pynwb, so will let you know how that goes...

**Comment by rly** [comment]
We have recently built infrastructure for building custom extensions to the NWB standard. We think this would suggested change would be most appropriate as an extension. Please let us know if you have any questions. https://pynwb.readthedocs.io/en/latest/extensions.html
