### ISSUE TITLE
remove PlaneSegmentation and just use ImageSegmentation to hold rois

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#158]
I'm bringing some Ca data into NWB and I am wondering what is the purpose of `PlaneSegmentation`? Why couldn't we just add rois to the `ImageSegmentation` object directly? Also, can we generalize the rois so that they are not constrained to be co-planar? ROIs sometimes exist across 3 dimensions.

**Comment by nicain** [comment]
@neuromusic wanna weigh in on this one?  I know you have thought alot about it...

**Comment by jonc125** [comment]
See also #118 #59 #156
