### ISSUE TITLE
How to store video?

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#159]
What would be the best way to store e.g. an avi video of a behaving subject? The current options I see are 

1) Read with opencv (or similar) and store frames as an `ImageSeries` in hdf5. This is pretty straightforward but will create a very large file. This can perhaps be mitigated by optimized chunking and compression settings.

2) Store as an external file in `ImageSeries`. I'd like to do this, but it looks like `ImageSeries` expects image formats (e.g. tiff, png, jpeg) not video formats. Video formats also contain time information, which would be redundant with `ImageSeries.timestamps`, and may contained sound, which would be undocumented.

Would it make sense to create a new type for referencing external video files? This would be similar to `ImageSeries` but would not contain time information, since that is within the external file, and would have a option to mark if the video has sound.

**Comment by kir0ul** [comment]
I would be very much interested in this new type for referencing video files :slightly_smiling_face:
