### ISSUE TITLE
Update Interface classes to use default_name instead of fixed name

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#16]
**[Hackathon]** To support processing modules with multiple Interfaces of the same type, all Interfaces should be changes to use a *default_name* instead of a fixed *name* (i.e., move value from *name* to *default_name* key). As such, all Interfaces should also have a neurodata_type_def (this should already be the case). 

**Note** Need to also add a note to the release notes of the format to describe this change.

**Comment by ajtritt** [comment]
48dc3348563a849066eb95db5264f5bcef8fee40

reformat script now specifies this. 

[pynwb: 0d934a4c93af00c9e29af08e84d944a1879ce714](https://github.com/NeurodataWithoutBorders/nwb-schema/commit/48dc3348563a849066eb95db5264f5bcef8fee40)
modifications have been made to DatasetSpec and GroupSpec in form.spec to support this ]
