### ISSUE TITLE
move Device to more general location

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#166]
`Device` is used by `ecephys`, `icephys`, and `ophys`. At this point it lives in `ecephys`, which is confusing because you have to import it from there, even if you are just dealing with ophys data. I think it should be moved to a more general place in the schema. Which would be most appropriate: `base`, `file`, or `misc`?

This is a copy of https://github.com/NeurodataWithoutBorders/pynwb/issues/443 reproduced here because this is more of a schema issue than a pynwb issue.

**Comment by oruebel** [comment]
Sounds reasonable.
