### ISSUE TITLE
Are ImagingPlane.optical_channel and ImagingPlane.device redundant?

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#167]
I was just about to correct the device field of `ImagingPlane` to be a reference to the `Device` object instead of a `str`, when I realized that the entire field might be redundant with `OpticalChannel`. I'm not experienced enough with ophys data to make the call, but it seems to me any of the relevant device information could be put in the `OpticalChannel` object.

**Comment by bendichter** [comment]
also @jonc125

**Comment by jonc125** [comment]
No, I think these are different (although the documentation could be better!). Each imaging plane is captured by a particular device (microscope) - this is given by `.device`. The data captured for a single plane can contain multiple channels (e.g. red, green) but these would all come from the same device.
