### ISSUE TITLE
Rename Module

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#17]
**[Hackathon]** To ease intuition *Module* should be renamed to more directly identify the purpose of a *Module*. 

**Proposed new name**  

* *ProcessingModule* --- i) would help indicate purpose of module and ii) preserve original base naming (i.e, Module)

**Comment by ajtritt** [comment]
de360e1b14a885dd6f250c289477558411970f88

Modified reformat script to renamed Module to Processing Module, and updated YAML specs
