### ISSUE TITLE
Release notes describe Trial Data Support 

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#170]
Update schema release notes to describe changes made to improve support of trial-based data. See
https://github.com/NeurodataWithoutBorders/pynwb/pull/536

**Comment by oruebel** [comment]
See also #173 for details on the schema changes

**Comment by bendichter** [comment]
How would you guys feel about a release soon to make the trials truly
official?

**Comment by oruebel** [comment]
I don't think we'll get a release done this week, but yes, we should probably do a release next week.
