### ISSUE TITLE
schema docs not building

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#174]
**Bug**
The schema docs are currently not building. I can build them locally on my labtop with the latest version of nwb-docutils and PyNWB, i.e., we may just need to update PyNWB on ReadTheDocs to fix the issue. The problem appears to be with "relaoding" the namespace ``core`` from the schema repo (which has already been loaded from the schema that ships with PyNWB).

See https://readthedocs.org/projects/nwb-schema/builds/7429637/

**Comment by bendichter** [comment]
may be related to https://github.com/NeurodataWithoutBorders/pynwb/issues/541

**Comment by oruebel** [comment]
Closing. Schema docs are building again after the update release of PyNWB.
