### ISSUE TITLE
support for boolean data type

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#175]
I don't see a category for boolean datatype in the schema language [data type support list](https://schema-language.readthedocs.io/en/latest/specification_language_description.html?highlight=boolean#dtype). Would it be possible to add this? HDF5, python, h5py, and matlab all support boolean representation, so I think it would be pretty straightforward.

**Comment by oruebel** [comment]
Fixed in https://github.com/NeurodataWithoutBorders/pynwb/pull/691
