### ISSUE TITLE
FeatureExtraction object

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#176]
I have a few practical questions about the [FeatureExtraction object](https://pynwb.readthedocs.io/en/latest/pynwb.ecephys.html#pynwb.ecephys.FeatureExtraction). The documentation suggests that this structure is appropriate for storing principle component analysis (PCA) results, however I think this structure is non-ideal for that purpose. PCA data would require two datasets, one for projection (eigenvectors) and one for activation (eigenvalues). The object only has room for a single `ndarray`, `features`, so it is not clear how to fit PCA results into this structure without extending it. Also, activation will usually be over time, so this should probably use a `TimeSeries` structure. The FeatureExtraction object has a field `times`, which I believe deviates from the pattern of NWB, since NWB generally allows for `timestamps` or (`rate` & `starting_time`).

Perhaps it doesn't make sense to try to anticipate the form of the various feature extraction methods. Would it be possible and practical to create a meta-type that is meant to be extended and simply categorizes data as such but imposes little other structure? Was that the intention of this class? Is this the purpose of [AbstractFeatureSeries](https://pynwb.readthedocs.io/en/latest/pynwb.misc.html?highlight=Annotation#pynwb.misc.AbstractFeatureSeries)? That seems a more appropriate structure actually and I prefer its placement in `misc` as well.

**Comment by oruebel** [comment]
See also https://github.com/NeurodataWithoutBorders/nwb-schema/issues/47

I agree that FeatureExtraction is not well suited for matrix factorizations. I think we need a new type for this.

**Comment by rly** [comment]
This is a great opportunity for an extension.
