### ISSUE TITLE
TimeSeries discrete vs continuous vs step

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#177]
I am working with MWorks data where a sample is stored only when a value changes. I'd like to store these as TimeSeries. I usually think of TimeSeries as values that you could interpolate smoothly between the values. Would it be possible to add a flag for interpolation using previous values? For example

This data:

data = [0, 1, 0, 1]
timestamps = [1, 2, 3, 4]

I would usually upsample using interpolation:

data =  [0, .5, 1, .5, 0, .5, 1]
timestamps = [1, 1.5, 2, 2.5, 3, 3.5, 4]

but I want to indicate that it should be upsampled this way, using the previous value:

data = [0, 0, 1, 1, 0, 0, 1]
timestamps = [1, 1.5, 2, 2.5, 3, 3.5, 4]

**Comment by ajtritt** [comment]
I don't know what MWorks data is, but it sounds like this is more of event-based data. Perhaps an extension would be appropriate for this.

**Comment by bendichter** [comment]
Yes, that is the case for many of the variables in the system, but some of the data is eye tracking  and t really should be a TimeSeries but is stored as events in MWorks.

**Comment by t-b** [comment]
IMHO interpolation is out of the scope for NWB. It should just store my data, neither interpolate nor do lossy compression or similiar.

**Comment by oruebel** [comment]
I agree that performing interpolation of data is out-of-scope of NWB and should be the role of libraries that sit on top of the format. In that regard, I don't think the format should dictate to the user which interpolation they should use. 

That all being said, I think the problem that @bendichter  is raising is a slightly different one. The question is not which interpolation to use (that decision is up to the user) but that the description of the data is missing metadata to allow him to programmatically decide which kind of interpolation method may be appropriate. For most data one could argue that this is implicit in the extension. The question, however, is whether this is something that should be made explicit, e.g., via an attribute on the data that indicates whether the data values in the timeseries are "continuous" or "discrete"

**Comment by bendichter** [comment]
Yeah that's right, I think that's a better way to put it. It's more a description of the data, not explicit instructions for interpolation. I'd like to have enough information in the data to know what would be an appropriate way to plot it. The options so far would be:

continuous: line plot (e.g. LFP)
discrete: scatter plot (e.g. behavioral events)
continuous-forwards/continuous-backwards: [step plot](https://matplotlib.org/gallery/lines_bars_and_markers/step_demo.html#sphx-glr-gallery-lines-bars-and-markers-step-demo-py) (e.g. MWorks events)

**Comment by t-b** [comment]
@bendichter @oruebel Thanks both for the clarifications. This makes sense to have.

**Comment by bendichter** [comment]
This issue has come up for the Allen Institute as well: https://github.com/AllenInstitute/AllenSDK/issues/1410. In this context, they are reporting speed in intervals defined by the original sample times. They want to say that the speed is x0 from t0 to t1, x1 from t1 to t2, etc.

**Comment by rly** [comment]
How do you propose we tackle this? One possibility is having a text attribute on `TimeSeries.data` that can have optional value "continuous", "discrete", or "step-forward" (like an enumerated type). The default value would be "continuous", and for certain subtypes designed around events, the default value would be "discrete". Another possibility is to have a new subtype for `TimeSeries` for step-forward data.

**Comment by bendichter** [comment]
I like the idea of adding an optional attribute to `TimeSeries.data` with those values. I'd prefer to have it missing my default, since there are actually a number of discrete timeseries (at least until we push out the `Events` object)

**Comment by rly** [comment]
Ah, right. Having it missing by default for now makes sense.
