### ISSUE TITLE
store electricalseries data as int16

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#178]
It's pretty common for acquisition data to be stored as `int16`, however this does not appear to be allowed by the schema. To store data I must convert to single precision float, which eats up a lot more memory than necessary. Can we lift this restriction?

**Comment by oruebel** [comment]
Which TimeSeries type are you referring to? As far as I remember the base TimeSeries does not restrict the data type that should happen in the specific subtypes.

**Comment by bendichter** [comment]
@oruebel You're right, I meant `ElectricalSeries`. It's generally LFP data that has this issue.

**Comment by oruebel** [comment]
@bendichter as far as I can tell the schema only says ``dtype: number`` which if I remember correctly should not restrict whether you are using an int or float. @ajtritt is this correct? Looking at PyNWB, I believe it should currently also allow any array_data for ElectricalSeries.

**Comment by bendichter** [comment]
I was looking at the schema here:
https://nwb-schema.readthedocs.io/en/latest/format.html#electricalseries

And here: https://github.com/NeurodataWithoutBorders/pynwb/blob/f91e0693259f9fef5e13697f15d3b2507385acfb/src/pynwb/data/nwb.ecephys.yaml#L22

Where are you seeing `dtype: number`?

**Comment by ajtritt** [comment]
This is what I see in the YAML:
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/997b52423ce242f62cd861c948731ba57aea5738/core/nwb.ecephys.yaml#L22

The RTD docs also inidicate *ElectricalSeries.data* is restricted to dtype *float*. As long as *ElectricalSeries.data.unit* correctly reflects the data stored, I think this restriction should be lifted

**Comment by bendichter** [comment]
Yes, using `int16` will require use of `conversion` for `units` to be correct, and we already have that built into the format so I don't see a problem there.

**Comment by bendichter** [comment]
What's the syntax for allowing any numeric format?

**Comment by ajtritt** [comment]
At one point it was `number`, but that was dropped for other technical issues it presented. The plan was to revisit it at some point... I guess now is that time.

**Comment by oruebel** [comment]
Sorry for the confusion on my end, Firefox had cached the schema docs for me so I still saw the old version with ``dtype: number``

**Comment by oruebel** [comment]
This has been fixed in https://github.com/NeurodataWithoutBorders/pynwb/pull/782
