### ISSUE TITLE
Rename and extend Interface

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#18]
**[Hackathon]** 
* *Interface* should be renamed to ease intuition. 
* The new class should be made base type of *TimeSeries* as well. This would allow current interfaces stored in modules to also become TimeSeries. This would also ease adding support for data provenance as a common concept to the format.

**Proposed Changes**
* Rename *Interface* to  *DataContainter* or  *NWBContainter* 
* Change *neurodata_type_inc* of *TimeSeries* to *NWBContainer* and remove the *source* attribute from the spec of *TimeSeries* as the attribute will be inherited from *NWBContainer*

**Comment by ajtritt** [comment]
72a58a3e03271ac660628697bfaba3ac7556d091

Renamed *Interface* to *NWBContainer* in convert script, and updated spec YAML

Made all base types extensions of *NWBContainer*
