### ISSUE TITLE
Release Notes: Document UnitTimes Refactor

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#190]
Describe refactoring of UnitTimes including the addition of VectorData and VectorIndex. See
https://github.com/NeurodataWithoutBorders/pynwb/pull/382 and https://github.com/NeurodataWithoutBorders/nwb-schema/issues/117

**Comment by bendichter** [comment]
This might help

![unittimes](https://user-images.githubusercontent.com/844306/46322976-a7b95d00-c587-11e8-9340-0416dbd7bac6.png)

**Comment by oruebel** [comment]
@bendichter thanks for the figure! I'll add this figure to the release notes as well since it illustrated nicely the basic concept.
