### ISSUE TITLE
Addition of Interval series to SpikeWaveform and ElectrodeGroup objects

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/nwb-schema#2]
Originally reported by: **Loren Frank (Bitbucket: [lmfrnk](https://bitbucket.org/lmfrnk), GitHub: Unknown)**

----------------------------------------

There are a number of cases when a user would need to know exactly when a particular SpikeWaveform or ElectrodeGroup is valid.  As an example, a given unit might be clusterable for only part of the time that it's ElectrodeGroup is valid, and those times may be distributed into multiple, disjoint periods.  Similarly, an ElectrodeGroup might be valid for a part of a definied Epoch, and right now there is no way to indicate that is the case.

Note that as there might be multiple intervals where one of these objects was valid, we would need an integrated IntervalSeries, not an integrated Epoch object.

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/nwb-schema/issue/2

**Comment by neuromusic** [comment]
this is highly relevant to the masking discussion we were having earlier, @nicain
