### ISSUE TITLE
possible to have multiple valid dtypes?

### ISSUE THREAD

**Issue by NileGraddis** [NeurodataWithoutBorders/nwb-schema#209]
This is an issue that @JFPerkins and I ran into with imagemasks. The dtype is [specified as float](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/data/nwb.ophys.yaml#L4), which makes sense for representing a weighted mask. However, if we have an unweighted mask or one with a discrete enumeration of possible weights it would be more space efficient to store the roi masks as an integer type.

This leads to a general question: can we have multiple valid dtypes for a dataset in the spec? In the schema docs it appears that valid dtypes must be drawn from [a list of primitive types](https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/docs/language/source/specification_language_description.rst#dtype) and we can't find any references to union types over those.

**Comment by ajtritt** [comment]
As of now, that is not possible. You would probably need to modify [DtypeSpec](https://github.com/NeurodataWithoutBorders/pynwb/blob/f671b8d7c8692e48fadd3e6314856ff3bd642421/src/pynwb/form/spec/spec.py#L522) and/or the classmethod [build_const_args](https://github.com/NeurodataWithoutBorders/pynwb/blob/f671b8d7c8692e48fadd3e6314856ff3bd642421/src/pynwb/form/spec/spec.py#L576).

The use case you describe might be better addressed with a different neurodata_type though. Do weighted masks get treated differently than an unweighted mask or a mask with an enumerable set of values? Do they represent different results? Encoding these different mask types would be better handled with different neurodata_types than primitive data types.

**Comment by ajtritt** [comment]
@bendichter no we don't, but I created #658 for the necessary changes to PyNWB

**Comment by bendichter** [comment]
@NileGraddis FYI I moved this to the nwb-schema repo using the new github feature to move issues. I'm trying to move issues that involve changes to the schema here since they are relevant to other groups e.g. matnwb.

**Comment by oruebel** [comment]
https://github.com/NeurodataWithoutBorders/pynwb/pull/782 addresses the issue of allowing numierc dtype. However, it does not address the issue raised with actually adding dedicated types for different kind of mask, i.e., FuzzyMask, BinaryMask, and MultiLableMask
