### ISSUE TITLE
add "allowable_values"

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#210]
The schema should be able to specify a list of allowable values for an attribute. For instance, for sex I would like to limit the allowable values to 'M' and 'F' to avoid having to parse across files that mark sex differently e.g. "male", "m", "man", etc.

**Comment by oruebel** [comment]
This issue pertains also to ongoing discussion regarding support for ontologies for fields. I think here what you are asking for is basically to support enumerated dtypes as part of the spec where you would, e.g.,  provide a list of the valid values as part of the specification of the dtype, correct?

**Comment by rly** [comment]
Enumerated types need to be implemented in HDMF to support this request https://github.com/hdmf-dev/hdmf
