### ISSUE TITLE
storing phase and amplitude

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#227]
Can we talk about how we store spectral band (e.g. theta phase and amplitude). There is an object called `FilteredEphys` in the `ecephys` module, which would seem to store this information:

> Ephys data from one or more channels that has been subjected to filtering. Examples of filtered data include Theta and Gamma (LFP has its own interface).

however on closer inspection it appears that this object is meant to store literally the filtered signal (the signal after a bandpass filter), not the phase or amplitude, because the object holds electrical_series objects, which are in units Volts, and there is no way of indicating if the signal is amplitude or phase. 

While it would be possible to get the phase and amplitude info from this filtered signal, this approach makes some assumptions about how the phase and amplitude are computed that are not true in all cases. Also, in my experience it is common for labs to store phase and amplitude directly as intermediate data.

This could of course be handled through extensions, but it seems like something that might be of general use to standardize across labs. I think this can be done in a non-schema-breaking way. The challenge is that these bands are computed differently lab-to-lab. For instance, we would need to account for the fact that labs tend to have different definitions of where the limits of the canonical band are. Actually, `ecephys.FeatureExtraction` is pretty close to what we need. It already has data of shape `[time x electrode x feature]`. Here is my proposal for how to extend it.

adding to ecephys:

```
LFPSpectralAnalysis(FeatureExtraction):
    band_limits: ([float float],...)
    metric: str
         recommended: phase, amplitude, power
    timeseries: link to raw signal
    band_name (optional): [str, str,...]
        recommended: alpha, beta, gamma, delta, theta, high gamma
```
The idea is for this structure to accommodate two different use-cases. The first is where we are looking at canonical bands (theta, gamma, etc.). In this case, `band_name` should be entered. The second is when a full spectrogram (e.g. the results of an STFT) is provided. In this case, the `band_names` can be omitted. The way I have proposed here, whether this is a phase or amplitude is indicated by the `metric` field. Since we don't yet have enumerated types, this must be a free field, which is not ideal. Alternatively we could have `LFPSpectralPhase` and `LFPSpectralAmplitude` inherit from `LFPSpectralAnalysis`.

You would use different objects for different types of spectral analysis (e.g. wavelet vs. Hilbert). Perhaps we could sub-class this with a few common ones, like STFT, and allow for explicit storage of variables e.g. window_len, window_function, window_overlap, etc. but this will be difficult to standardize across labs and might be better done with an extension.

Since this requires `electrodes` and is in the `ecephys` module, a separate structure would need to be made for storing the spectrogram of behavioral data, e.g. speech, but it would look very similar to this one.

@ajtritt I know you were thinking about this. Were you thinking of doing this another way?

**Comment by JesseLivezey** [comment]
@bendichter would `LFPSpectralAnalysis` allow complex dtypes or were you imagining that analytic amplitudes or wavelet signals would always be stored as an amplitude and phase separately? Then `LFPSpectralAnalysis` would be only for real-valued band-passed signals and not transformed-bandpassed signals.

**Comment by bendichter** [comment]
@jesselivezey I figured users almost always will use the complex signal to compute aa and phase, and you can always back compute the complex signal if you really need it. Are there situations where it would be better to store the complex signal instead?

**Comment by JesseLivezey** [comment]
> Are there situations where it would be better to store the complex signal instead?

I don't think so. Your plan sounds good to me.

**Comment by bendichter** [comment]
Now I'm thinking we could just call it `SpectralAnalysis`, have it inherit from `TimeSeries`. This will allow us to use this for other purposes as well. We don't really need to link to electrodes if we already include the source timeseries
