### ISSUE TITLE
combine SpikeEventSeries and Clustering

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#239]
## 2) Feature Request

How would people feel about folding `Clustering` into `SpikeEventSeries` by removing `Clustering` and adding a `SpikeEventSeries.cluster` field of dtype `int`? We could make `data` optional, in case a user only wants to store the times and not the waveforms (this is pretty common).

This would:
1) Make the relationship between a spike time and the spike waveform more explicit
2) Remove redundant `timestamps` that is currently duplicated across the two objects
3) Resolve the issue that `Clustering` should have an `electrodes` field (https://github.com/NeurodataWithoutBorders/nwb-schema/issues/194)
4) Resolve the issue that `Clustering` should be a `TimeSeries`(https://github.com/NeurodataWithoutBorders/nwb-schema/issues/112)

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by ajtritt** [comment]
The only thing I am unsure of is making `SpikeEventSeries.data` optional. If a SpikeEventSeries doesn't have `data`, then it fails to meet the requirements of a `TimeSeries`.

**Comment by tjd2002** [comment]
I'm all for removing 'Clustering'. I've been thinking of Clustering+SpikeEventSeries as being superseded by the new Unit table (for Unit metadata including clustering metrics) and UnitTimes (for spike times of each clustered unit), and expecting that all that older stuff would soon be deprecated. We've been using Unit + UnitTimes to store the output of clustering.

I think this use of Unit + UnitTimes handles the case where there is no per-spike waveform data. So we could keep SpikeEventSeries and add the '.cluster' field as proposed, and then only use it when storing waveforms. I think this would mean we don't have to worry about the no-data case discussed above.

**Comment by tjd2002** [comment]
Conversation seems to be continuing over at #194, in case anyone else is following along.

**Comment by stephprince** [comment]
Closing because `Clustering` has been deprecated.
