### ISSUE TITLE
tool for creating partial nwb files

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#240]
### Problem/Use Case
I have heard from several groups that they have the desire to store stimulus data in an external file and link to the file. This is important for them because they often play the exact same stimulus and do not want to duplicate the data for every NWB file. Sometimes the stimulus file is big (e.g. videos) and even when it is not that big it's a bad idea to duplicate data. This is a critical issue for many labs. (@the-moliver)

Another application for externally linking files is for subject data. For instance, brain imaging data that is constant for a subject could be stored externally and linked to. I have this issue with the Chang Lab, where I would really like to not store the cortical surface mesh of each subject every time I record an experimental block (there are often >100 per subject).

We support this! (#408) However it's not easy to create the file that is to be linked to and there isn't really a convention for doing this. I would like a tool that writes a file containing a single dataset or a small set of datasets. This file is not strictly nwb-compliant because it does not contain all the necessary parts (processing, acquisition, etc.) but the dataset(s) created are compliant and fit perfectly in to an nwb file when linked to. I propose that these files be designated by .nwbaux and we should have a tool to create them:

```python
with NWBHDF5IO('subject_001.nwbaux', mode='w') as io:
    io.write_aux_file(container_or_list_of_containers)
```

I'd like to open the discussion here. Is this a good idea? Do others think this would be useful? Any suggestions for a better naming convention (I'd prefer .nwb-aux but is a dash in the file suffix a bad idea?)

**Comment by bendichter** [comment]
I guess there are really two distinct issues: the name and the schema. I think it would be useful to indicate in the filename that this file is meant to be linked to. That way it will be less likely to get separated from the session files that need it and it won't be confused for a complete session file itself. However I take your point about the contents and I suppose there's really no harm in generating an entire nwb file. Some of the fields eg "creation date"  should be in these files too. Others like "starting time" only make sense for session data and won't make sense for the aux files. Should we use a standard null value for these?

**Comment by bendichter** [comment]
@tjd2002

**Comment by tjd2002** [comment]
@dimitri-yatsenko
