### ISSUE TITLE
accessing spike waveforms from units table

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#248]
We need a standard way to store spike waveforms in a way that they are linked with spike times and to their unit identity. Since we are moving to deprecate `Clustering`, we can't rely on using a shared index between `Clustering` and `SpikeEventSeries`, and we will need to find another way to offer this capability.

One solution might be to add a column to `Units` that is called `'waveforms'` and every cell is a number_of_spikes x number_of_electrode x number_of_samples matrix. An issue with this approach, however, is that we would not be able to store unsorted spike waveforms by the same mechanism. We could also allow `SpikeEventSeries` specifically for unsorted spikes, but then we have two different ways of storing spike waveforms, and we are trying to avoid that.

Another approach would be to have the `'waveforms'` column provide references to rows of the `SpikeEventSeries` dataset. An advantage of this is that we would have the spikes only in a single place. One disadvantage is that it might be tricky to work out the electrodes issue. Is there a single `SpikeEventSeries` or multiple, one for each electrode group. If there are multiple, we will need to work out a way for the column to reference different objects between rows. If there is only one, most of the channels will contain zeroes, since spikes are only picked up on a single channel group at a time, and there will be a mismatch between the '`electrodes'` column and the dimensions of the waveform.

**Comment by ajtritt** [comment]
> An issue with this approach, however, is that we would not be able to store unsorted spike waveforms by the same mechanism. We could also allow `SpikeEventSeries` specifically for unsorted spikes, but then we have two different ways of storing spike waveforms, and we are trying to avoid that

I don't think this presents two different ways of storing the same information, unless you equate sorted spikes and unsorted spikes. The purpose of `SpikeEventSeries` has always been for unsorted spikes. `Units` by definition is sorted, so storing sorted spike waveforms here fits.

Adding this to `Units` just means adding two more optional datasets: `waveforms` (a `VectorData` and `waveforms_index` (a `VectorIndex`).

**Comment by bendichter** [comment]
OK I'm happy with that. Do you anticipate any issues with having a 2D ragged array? (one dim varies, the other is constant length)

**Comment by oruebel** [comment]
Just for my own understanding, the ``waveform`` column in ``Units`` would be in addition to the ``waveform_mean`` that is currently in ``Units``?

**Comment by ajtritt** [comment]
in addition to `waveform_mean`

**Comment by ajtritt** [comment]
- [ ] Add links to `SpikeEventSeries` in `ElectrodeGroup`
- [ ] create `UnitSeries`, with link to related `SpikeEventSeries`
  - include reference to `Units` table
- [ ] Add link to related `UnitSeries` to `SpikeEventSeries`

**Comment by bendichter** [comment]
Just to bring this convo up to speed. We decided to solve this problem by using the electrode_group column of the `Units` table. The reference flow will be:
 unit -> electrode_group -(link)-> `SpikeEventSeries` -(link)-> `UnitSeries`

**Comment by bendichter** [comment]
using https://github.com/NeurodataWithoutBorders/nwb-schema/pull/245

**Comment by tjd2002** [comment]
Sounding good...

~Does `UnitSeries`  inherit from `SpikeEventSeries`? Or does it contain indexes into the related `SpikeEventSeries`?~

Err, let me go read the PR at #245 and try to understand this myself.

**Comment by tjd2002** [comment]
So, as I understand it, in the latest proposal, we are not adding any new columns to the Units table.

Instead, if you wanted to recover the waveforms for an individual unit, you would follow the reference flow @bendichter outlined above ( unit -> electrode_group -(link)-> `SpikeEventSeries` -(link)-> `UnitSeries` ). Then you would parse the data column of the `UnitSeries` to find the indexes (into the `SpikeEventSeries`) for a given unit, and go look up the waveform data from the SpikeEventSeries.

In general I like this: I think it's good to have all waveforms stored in one place (using an existing NWB data structure!), and to index into it with a single UnitSeries.

However, it is currently possible to have more than one pynwb.misc.Units table in an NWB file (e.g. to store multiple different clusterings of the same data), and I'm not sure how this is proposed to be handled. That is, in this scheme, how can a given Units table indicate _which_ `UnitSeries`  should be used? By the time you've followed the links through electrode_group and `SpikeEventSeries` you've lost that information).

I note that the UnitSeries proposed in #245 _does_ have a link to its corresponding Units table, so I suppose you could grab all the related UnitSeries from the SpikeEventSeries and look for a match to the Units table being inspected? (This would only work in the case where there is at most 1 UnitSeries per Units table (which I _think_ sounds reasonable, but should probably be formally stated somewhere)).

**Comment by bendichter** [comment]
Yes, all that is correct, except I think the constraint is rather that you cannot have more than one `Units` table per `UnitSeries` (you can create multiple `UnitSeries` objects so this should not be a problem)

**Comment by bendichter** [comment]
`SpikeEventSeries` currently takes an argument `electrodes` that is a `DynamicTableRegion` of the `electrodes` table (via `ElectrodeSeries` inheritance). Since we are proposing to link `SpikeEventSeries` to `ElectrodeGroup`s, does it make sense to remove this? This would be a breaking change. We could make it optional and deprecated.

**Comment by bendichter** [comment]
Trying to link from `UnitSeries` back to `SpikeEventSeries` caused a circular import error. I don't think that link is necessary so I am not going to add it.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-710d11685339> in <module>
----> 1 from pynwb.misc import UnitSeries

~/dev/pynwb/src/pynwb/__init__.py in <module>
    229 
    230 
--> 231 from . import io as __io  # noqa: F401,E402
    232 from .core import NWBContainer, NWBData  # noqa: F401,E402
    233 from .base import TimeSeries, ProcessingModule  # noqa: F401,E402

~/dev/pynwb/src/pynwb/io/__init__.py in <module>
      1 # flake8: noqa: F401
----> 2 from . import base as __base
      3 from . import core as __core
      4 from . import file as __file
      5 from . import behavior as __behavior

~/dev/pynwb/src/pynwb/io/base.py in <module>
----> 1 from .core import NWBContainerMapper
      2 from .. import register_map
      3 
      4 from ..base import TimeSeries, ProcessingModule
      5 from ..form.build import LinkBuilder

~/dev/pynwb/src/pynwb/io/core.py in <module>
      5 from .. import register_map
      6 
----> 7 from pynwb.file import NWBFile
      8 from pynwb.core import NWBData, DynamicTable, NWBContainer, VectorIndex
      9 

~/dev/pynwb/src/pynwb/file.py in <module>
     11 from .base import TimeSeries, ProcessingModule
     12 from .epoch import TimeIntervals
---> 13 from .ecephys import ElectrodeGroup, Device
     14 from .icephys import IntracellularElectrode, SweepTable, PatchClampSeries
     15 from .ophys import ImagingPlane

~/dev/pynwb/src/pynwb/ecephys.py in <module>
      9 from .core import NWBContainer, NWBDataInterface, MultiContainerInterface, DynamicTableRegion
     10 from .device import Device
---> 11 from .misc import DecompositionSeries
     12 
     13 

~/dev/pynwb/src/pynwb/misc.py in <module>
      7 from .base import TimeSeries, _default_conversion, _default_resolution
      8 from .core import NWBContainer, ElementIdentifiers, DynamicTable
----> 9 from .ecephys import SpikeEventSeries
     10 
     11 

ImportError: cannot import name 'SpikeEventSeries'
```

**Comment by bendichter** [comment]
@rly and I discussed a much simpler solution, which would be to have an optional "waveforms" column on the Units table. This would be for storing the waveforms of units that have already been sorted. `SpikeEventSeries` would continue to be used for storing waveforms of unsorted spikes.
