### ISSUE TITLE
Remove unit parameter of *ClampSeries and *StimulusSeries classes and hard code it

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/nwb-schema#260]
See https://github.com/NeurodataWithoutBorders/pynwb/issues/934.

**Comment by rly** [comment]
Just to be clear, do you mean to hard code the `unit` property of:
`VoltageClampStimulusSeries`, `CurrentClampSeries` to be V
`CurrentClampStimulusSeries`, `VoltageClampSeries`, `IZeroClampSeries` to be A

**Comment by t-b** [comment]
@rly Yes exactly.

**Comment by rly** [comment]
Actually, I think I messed up my last comment. Should the unit property of `IZeroClampSeries` be V?

**Comment by t-b** [comment]
@rly Sorry for the late reply. Yes the unit of `IZeroClampSeries` is indeed V.

**Comment by rly** [comment]
@t-b Great! Thanks for confirming.
