### ISSUE TITLE
Different standards for TwoPhotonSeries and PlaneSegmentation's "image_mask"

### ISSUE THREAD

**Issue by lawrence-mbf** [NeurodataWithoutBorders/nwb-schema#262]
Original issue by @kelsonSS in https://github.com/NeurodataWithoutBorders/matnwb/issues/142
>For the Ophys pipeline the raw data that is stored in TwoPhotonSeries is required to be in a Nframes by Y by X matrix while the ROI segmentation is in a NCells by X by Y matrix. This will cause errors and I suggest standardizing to the Nframes by X by Y format.
>This problem persists with 3D data and should be standardized to N by X by Y by Z

- TwoPhotonSeries data dimensions is `[[‘frame’, ‘y’, ‘x’], [‘frame’, ‘z’, ‘y’, ‘x’]]`
- PlaneSegmentation's `image_mask` dataset is ` [[‘num_roi’, ‘num_x’, ‘num_y’], [‘num_roi’, ‘num_x’, ‘num_y’, ‘num_z’]]`

The preferred style would be `['frame', 'x', 'y', 'z']` for TwoPhotonSeries data.

**Comment by rly** [comment]
@ln-vidrio Maybe I am missing something, but where is TwoPhotonSeries data dimensions specified as [[‘frame’, ‘y’, ‘x’], [‘frame’, ‘z’, ‘y’, ‘x’]] ? I don't see it in the schema...

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/3f92c4a611f5b1835cc025916030b0be3a414ad7/core/nwb.ophys.yaml#L1-L35

**Comment by bendichter** [comment]
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/3f92c4a611f5b1835cc025916030b0be3a414ad7/core/nwb.image.yaml#L51-L58

**Comment by bendichter** [comment]
It's inherited from ImageSeries

**Comment by rly** [comment]
Ahh. Thanks. If we change this, should we also change the ordering of dims of Image to (x, y) to be consistent across types?

**Comment by bendichter** [comment]
Sure, that makes sense
