### ISSUE TITLE
DRAFT: Add OnePhotonSeries neurodata_type

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#283]
Similar to [TwoPhotonSeries](https://pynwb.readthedocs.io/en/stable/pynwb.ophys.html#pynwb.ophys.TwoPhotonSeries) but for handling one photon calcium imaging data from the [Miniscope](http://miniscope.org/index.php/Main_Page).

Details and differences with TwoPhotonSeries need to be fleshed out.

**Comment by bendichter** [comment]
It should at least have a link to a `Device`

**Comment by rly** [comment]
Proposed solution: add optional link to Device in ImageSeries. add OnePhotonSeries with related metadata. Make an extension for OnePhotonSeries and we could fast track it into the core.

**Comment by bendichter** [comment]
From talking with @chrapkiewicz, we have some more specific metadata requirements:

OnePhotonSeries need to link to two different types of devices: Objective Lens and Camera. Objective Lens can be the same as in 2p. It either needs to be specified with a model number (which fully defines it) or with:
* manufacturer: str
* magnification: float
* numerical aperture: float

Unlike 2p, `OnePhotonSeries` would also need an associated camera. Again, this could be mostly specific by a model number, but in the absence of a model number these futures would be needed:
* quantum efficiency
* read noise (units: # electrons)
* pixels (I guess width and height would be best)

then there are two settings you might need to store:
* exposure time (this is often 1/frequency, but sometimes not)
* binning (combining pixels, could be 1,2,4 or 8)

finally, you should indicate power, which is generally <5 mW. Alternatively, you might want to store intensity, which is units mW/mm^2, but it sounds like power is more common

**Comment by chrapkiewicz** [comment]
Looks good to me. There are probably slightly different metadata for miniscopes and 1p microscopes for head-fixed experiments. 
In the latter case if that's a commercial body, the model should be known and what users are changing are: filters (excitation, emission, dichroic) and objective. A camera is easily upgradable and defines image properties and should be reported too. 

For custom microscope really the only extra part that needs to be reported is just a tube lens defined by a focal length (float) typically between 90 and 200 mm and a model.
