### ISSUE TITLE
related_publications should be a list

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#299]
similar to keywords. This would facilitate querying by publications. Right now you are instructed to concatenate multiple publications together into one big string. The change here would be similar to what was done for experimenters

**Comment by rly** [comment]
That makes sense. Any objections to bundling this into version 2.1.0?

**Comment by oruebel** [comment]
That sounds fine. Making this part of 2.1.0 sounds reasonable.
