### ISSUE TITLE
What to do about general/intracellular_ephys/filtering?

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#313]
In my search for unmapped nested types in PyNWB, I noticed that within the general/intracellular_ephys group, there is a dataset called `filtering` that is not referenced in PyNWB and therefore AFAIK cannot be set or accessed. 

There is also a `filtering` dataset on the `IntracellularElectrode` type for electrode-specific filtering.

I assume the`NWBFile.general.intracellular_ephys.filtering` dataset is used to specify the filtering for all intracellular electrodes rather than on a per-electrode basis. 

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/da3bcd72d63c83c512dd56e9959f409230c5756e/core/nwb.file.yaml#L344-L361

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/da3bcd72d63c83c512dd56e9959f409230c5756e/core/nwb.icephys.yaml#L193-L203

The general/extracellular_ephys/ group used to have a `filtering` dataset as well. This was removed in favor of per-electrode `filtering` in `ElectrodeTable`. 

Given this, we could either:
1. support setting/getting the `NWBFile.general.intracellular_ephys.filtering` dataset in PyNWB
2. deprecate the `NWBFile.general.intracellular_ephys.filtering` dataset

I support option 2 for consistency with extracellular ephys.
- Pro: cleaner and more usable spec
- Con: if all intracellular electrodes are filtered the same way, redundant information is stored.
- Con: someone using the Matlab API or other APIs may have data in the first `filtering` dataset

**Comment by rly** [comment]
@oruebel in the update to how intracellular ephys data is handled, I suggest we fold in a solution to this (minor) issue, which resurfaced today as I work through changes to the ObjectMapper.

**Comment by t-b** [comment]
I'm also in favour of per-electrode filtering.

**Comment by oruebel** [comment]
@rly @tb if I understand this correctly, then the proposed change is to deprecate ``NWBFile.general.intracellular_ephys.filtering`` with not other changes needed as the ``IntracellularElectrode`` already has a ``filtering`` field, correct? Can you create an issue on the icephys extension repo describing the change, and I can add it.  We should also update the Google doc with the proposal accordingly.

**Comment by stephprince** [comment]
`NWBFile.general.intracellular_ephys.filtering` was deprecated when ndx-icephys-meta was merged into the core schema: https://github.com/NeurodataWithoutBorders/nwb-schema/pull/470.
