### ISSUE TITLE
OpticalSeries does not allow for RGB

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#316]
The `dims` of `OpticalSeries` inherits from `ImageSeries`, which is:

```yaml
- - frame
   - x
   - y
- - frame
   - x
   - y
   - z
```
This makes it impossible to properly record the presentation of colored images. I would expect this to be the most common application of the neurodata_type. There are ways to present volumetric data to he subject, but presenting color images is much more common, and I am not aware of any groups using `OpticalSeries` to record the presentation of volumetric stimuli.

My preferred solution would be to change the shape of `OpticalSeries.data` to:

```yaml
- - frame
   - x
   - y
- - frame
   - x
   - y
   - r,g,b
```
This issue is currently blocking the Rutishauser lab, which is trying to write and publish a guide for converting data to NWB.

**Comment by rly** [comment]
This sounds good to me. 

I am also in favor of creating a VolumeSeries to handle the 3-D case of ImageSeries. That might prevent other issues when distinguishing between RGB images and grayscale volumes.
