### ISSUE TITLE
electrode position

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#325]
Right now the x,y,z columns of the electrodes table are ambiguous and under-utilized. The problem is that it's not clear what space they are supposed to belong to. The most common I've seen across datasets is to store the x,y position of an electrode on a probe. This is used by e.g. SpikeExtractors, kilosort, etc. to determine which electrodes are close enough to each other to potentially observe the same neuron. The other possible use is brain-space e.g. the Allen CCF. Eddie Chang stores x,y,z in brain space as well. This is less common to know, but obviously just as useful. I think we really need spots for both. The problem is right now we only have one set of x,y,z, and it isn't clear to a user which way it is intended to be used. Maybe we could add some optional columns like `group_x`, `group_y` that would only be valid within a group relative to the other electrodes in the group, or `device_x`, `device_y` that would be valid within a device.

**Comment by bendichter** [comment]
rel_x, rel_y, rel_z as optional cols of the electrodes table

pos as optional arg of `ElectrodeGroup`

**Comment by bendichter** [comment]
Pam helped address this on the CCF side. Here's a diagram from an Allen Institute documentation page:

http://help.brain-map.org/download/attachments/5308472/3DOrientation.png?version=1&modificationDate=1368132564812&api=v2

+x = posterior, +y = inferior, +z = right. Let's put that in the schema docs and api

**Comment by oruebel** [comment]
@bendichter do you think we need to add this to our best practices document?
