### ISSUE TITLE
Store reference of monopolar ElectricalSeries recordings

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#331]
Currently, NWB does not have a place to store information about the reference of `ElectricalSeries` recordings, whether it is a skull screw, a silver-chloride wire in the CSF, another electrode, an online common average, or another referencing scheme. The type and location of the reference are important for interpreting the data. For now, it would be easiest to store this information as a free-form string, named `'reference'` as a column on the `ElectrodeTable`. It would be optional, but I think it should be encouraged (perhaps in the best practices) that the information is provided in the dataset.

If the reference scheme changes mid-session, a new row in the `ElectrodeTable` should be made, just as if the position or impedance of the electrode changes mid-session. There is currently no way of linking rows as being from the same physical electrode, but perhaps the optional `rel_x`, `rel_y`, and `rel_z` attributes would help, since those should never change. 

@bendichter @oruebel thoughts?

**Comment by oruebel** [comment]
I assume the ``reference`` is the same across all electrodes within a group, i.e., would the reference not be part of the ``ElectrodeGroup`` instead? 

Also you mention that you need the type and location for the reference. If that is the case, then I think you probably would want a ``reference_type`` and a ``reference_location`` that are separate.
