### ISSUE TITLE
dtype of Data neurodata_type

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#347]
The dtype field is required for all datasets ([here](https://schema-language.readthedocs.io/en/latest/specification_language_description.html#sec-dataset-spec)), however it is often omitted. First of all, when we say a field is required, we need to determine whether that means it needs to be defined for that specific class, or it can inherit this feature. For "doc", it must be defined for each class. For "dtype", we might want to let the classes inherit it, but we still have a problem.

In nwb.image.yaml.GrayscaleImage > nwb.base.Image > nwb.base.NWBData > common.yaml.Data, none of these types define a dtype.

Should we instead say that dtype is optional for datasets? I will do this moving forward with the schema validator until we come to a decision as a group.

**Comment by oruebel** [comment]
> Should we instead say that dtype is optional for datasets

``dtype`` I think is treated as optional in cases where any dtype is allowable for the dataset. I think this would be the same as ``dtype=None`` This is the case for base neurodata_types, i.e., types that act mostly as abstract base types that are being extended later on. Saying that dtype is optional is I think fine, but we should make it clear in the docs that it should be specified for all concrete types (at least as a best practice). 

In that sense,  at least that ``nwb.image.yaml.GrayscaleImage`` does not have a dtype seems like a bug.  Possibly even``nwb.base.Image`` should also specify the dtype (depending on if the subtypes use a consistent format).

**Comment by bendichter** [comment]
I agree. So then there are two action items here:

1. Make `dtype` optional for datasets
2. Specify `dtype` for `Image` and `GrayscaleImage`
