### ISSUE TITLE
ImageSeries schema error

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#348]
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/76fc024c39815e5d3dfb62d958f9c451fa973570/core/nwb.image.yaml#L102-L109

`ImageSeries.format` is a dataset with a `default_value` attribute, which is [not allowed](https://schema-language.readthedocs.io/en/latest/specification_language_description.html#sec-dataset-spec). We could make it an attribute, but this might cause backward compatibility issues. Alternatively, we could allow datasets to have default values if they are text.

**Comment by oruebel** [comment]
I believe this is allowed in the schema language https://github.com/hdmf-dev/hdmf/blob/55dc7dd2b51f4725bd818fb58eb8d811319279a2/src/hdmf/spec/spec.py#L608 , i.e., this may be a bug in the schema language documentation instead

**Comment by bendichter** [comment]
fixed in cf5b1e2
