### ISSUE TITLE
TwoPhotonSeries.field_of_view schema error

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#349]
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/76fc024c39815e5d3dfb62d958f9c451fa973570/core/nwb.ophys.yaml#L16-L27

The "required" field is [not allowed](https://schema-language.readthedocs.io/en/latest/specification_language_description.html#sec-dataset-spec) for datasets.

**Comment by rly** [comment]
Fixed by #356
