### ISSUE TITLE
namespace/schema/neurodata_types list or no?

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#362]
The schema language says a namespace/schema/neurodata_type should be a list of of strings [here](https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/docs/language/source/specification_language_description.rst#schema) however the example shows not a list but a single string. We should either change the definition to allow either or we should change the example to be a list of length 1.

**Comment by oruebel** [comment]
I think both are technically allowed (i.e, just a string in case of list of length 1, and a list of strings otherwise), but for simplicity and to encourage best practices I think we should just change it to a list.
