### ISSUE TITLE
IZeroCurrentSeries stimulus description

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#372]
By definition, an `IZeroCurrentSeries` has no stimulus, so it should not allow for a "stimulus description"

cross-listed from https://github.com/NeurodataWithoutBorders/pynwb/issues/1130

**Comment by bendichter** [comment]
Also, isn't it odd for the stimulus description to be attached to the `CurrentClampSeries` at all? Shouldn't it be attached to the `CurrentClampStimulusSeries`? This would certainly be breaking backwards compatibility. Maybe include this change in 3.0?

**Comment by rly** [comment]
@t-b `stimulus_description` is an attribute on `PatchClampSeries`. Could you give an example of the information that would go in this attribute? Would it differ between the stimulus and the response? If it is the same, perhaps it would be more appropriate to have `stimulus_description` be an attribute of only the stimulus (or the sweep?).

**Comment by t-b** [comment]
https://github.com/NeurodataWithoutBorders/nwb-schema/pull/373#issuecomment-571542592.

`stimulus_description` holds in our case the name of the waveform used as stimulus. So something like `StimulusSetA_DA_0`. We currently store the same string for the stimulus/response pair (`XXXSeries` and `XXXStimulusSeries`). We need to have that attribute for `XXXStimulusSeries` as the response might be missing.

So in theory we could drop the attribute for `XXXSeries` but would need to ensure in that case that we have a corresponding `XXXStimulusSeries` for the same electrode and the same sweep. I don't think this is worth the hassle.
