### ISSUE TITLE
legacy pynwb naming in docs

### ISSUE THREAD

**Issue by ukos-git** [NeurodataWithoutBorders/nwb-schema#374]
Should the reference to `pynwb` be altered to `nwb-schema` in the sphinx documentation?

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/e67d9f4dc2bbbe4397bc3b6d1e169229d1b5d743/docs/format/Makefile#L12

**Comment by rly** [comment]
@ukos-git this should be fixed now. Thanks for that.
