### ISSUE TITLE
NWB version in nwb.file.yaml should be updated

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#390]
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.file.yaml#L10

The version here and in nwb.namespace.yaml should be updated to 2.2.1.

**Comment by t-b** [comment]
Isn't that version number something we would like to gather from a git tag or package version?

**Comment by rly** [comment]
@t-b how would one do that in YAML?

**Comment by oruebel** [comment]
I think doing this may require a Git workflow to automatically update the YAML files when a tag is being created.
