### ISSUE TITLE
global unobserved intervals

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#394]
It is a common issue that groups want to convert trialized data to NWB. This is not straightforward, because NWB generally wants continuous non-trialized streams of data. If you have the start times of each trial, you can recombine the data. Even if you recombine the data, you often end up with gaps, sometimes in a single modality and sometimes across modalities, depending on how the data was stored. If we do not properly mark the data as missing, you might end up with the impression that no events occurred in that window, and that could be very misleading and drastically impact results. So what is the best way to deal with missing information? Here are some mechanisms that are currently available.

* For `TimeSeries` types that have a constant sampling rate but have gaps, use the `timestamps` way of storing times and mark the gaps explicitly by having no timepoints in the gaps.
* The global `intervals/invalid_intervals` table indicates time intervals that should be omitted from analysis.
* The `Units` table has an optional column `obs_intervals`, which gives you unit-by-unit control to indicate when each unit is observed (and by contrast when they are not).

How should we handle it if there are windows that contain no spike data for any units? We could use `Units.obs_intervals`, but that would require us to repeat the same `obs_intervals` for each unit. I think it would be preferable if we use a global indicator, saying that there is no spike data for *any* unit in this window. Maybe the `/intervals/invalid_intervals` is better in this case? Maybe we should add a new dataset to`Units`?

**Comment by oruebel** [comment]
@bendichter can this be closed?
