### ISSUE TITLE
Release notes are not up-do-date

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/nwb-schema#397]
See https://nwb-schema.readthedocs.io/en/latest/format_release_notes.html.

**Comment by rly** [comment]
The docs will be fixed once pynwb 1.2.0 comes out. Unfortunately, hdmf_docutils imports the latest hdmf, which is not compatible with the latest pynwb. So docs generation for nwb-schema fails. In the meantime, you can look at: https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/docs/format/source/format_release_notes.rst
