### ISSUE TITLE
Change location and channel_location fields of ElectrodeGroup to list

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/nwb-schema#4]
Originally reported by: **Loren Frank (Bitbucket: [lmfrnk](https://bitbucket.org/lmfrnk), GitHub: Unknown)**

----------------------------------------

We often have multiple pieces of information for location (e.g. hippocampus CA1 proximal) so it would be useful if the location and channel_location fields could be a list instead of strings.  We could of course parse the strings, but I would think searching would be easier on lists.

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/nwb-schema/issue/4

**Comment by oruebel** [comment]
@ajtrtt is this part of #6. Should this ticket be closed?
