### ISSUE TITLE
Object id missing in format release notes

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#401]
In #285 it looks like we missed to mention object id in the release notes for the NWB format specification. We mention it in the storage release notes and link to the format release notes, but it looks like we are note actually mentioning the object id there.

**Comment by t-b** [comment]
While we are at it. Are the object IDs part of the YAML specification? I could not any mentioning of them.

**Comment by oruebel** [comment]
``object_id`` is a reserved attribute, similar to the ``neurodata_type`` and ``namespace`` attribute. The documentation for this is at  https://nwb-schema.readthedocs.io/en/latest/format_description.html#common-attributes and it is also listed in https://nwb-storage.readthedocs.io/en/latest/storage_hdf5.html

Reserved attributes are added by the specific storage backend (e.g., HDF5), rather than being part of the schema. A specific storage backend may add reserved attributes for a number of reasons e.g., to implement required features that are not natively supported by the backend.

**Comment by t-b** [comment]
Thanks. I did not know about reserved attributes. Does/should the validator care about reserved attributes? The NWB files MIES creates are currently without `object_id` but the validator also passes.

**Comment by oruebel** [comment]
Yes, I think the validator should ideally care about the reserved attributes. For ``neurodata_type`` and ``namespace`` that is basically covered by the fact that you can read the file (I don't think PyNWB would work without them), but for ``object_id`` I think we probably need a separate check.
