### ISSUE TITLE
Retinotopy improvements

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#407]
From Jerome Lecoq at the hackathon:

- [ ] `sign_map` should be optional
- [ ] phase maps and vasculature image are the most important. power maps should be optional
- [ ] improve documentation based on discussion with Jerome
- [ ] `focal_depth_image` should be optional

**Comment by bendichter** [comment]
I suggest we demote retinotopy to an extension. @rly, what do you think?

**Comment by rly** [comment]
I agree. This will take significantly more time to fix and meet user needs, so it would be best not to have it in the core schema until that is done. I am sure no one is using these types in NWB 2 -- these types do not roundtrip with PyNWB, so we would hear about bugs there if users were using it. Some users may be using it in MatNWB but we have not seen any evidence of that in the last couple of years. And there are no tutorials or known scripts that use these types in NWB 2. 

I suggest we first deprecate these types in the next minor version (2.3.0) with warnings in the APIs, even though this is a significant change. Then we work on the extension. In NWB 2.4.0, we would remove the types unless the extension is ready to be integrated. @oruebel @ajtritt thoughts?

**Comment by stephprince** [comment]
Closing because `ImagingRetinotopy` has been deprecated with https://github.com/NeurodataWithoutBorders/nwb-schema/pull/565.
