### ISSUE TITLE
prenatal age

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#412]
I am dealing with data that has different types of age, including prenatal. I propose adding an optional attribute to the `Subject.age` dataset that is "age_type". This could be populated with the possible values:

* "birth": standard age from birth. This is assumed if the age_type attribute is omitted, but is recommended if there is some ambiguity or if there are other sessions in the dataset that are prenatal.
* "gestational" : duration since the mother's last normal menstrual period
* "fetal": duration since conception
* Are there any other relevant forms of age?

Then we would encourage users to provide age in ISO 8601: `P(n)Y(n)M(n)DT(n)H(n)M(n)S`

e.g. 19 weeks `'P19W'`, 29 years is `'P29Y'`, 103 days would be `'P103D'`.

It would be nice if users could input this information with a `datetime.timedelta` object in pynwb. I don't know of any parser that goes back and forth between this and a python `datetime.timedelta`, but that doesn't sound very hard. That would also allow us to facilitate queries with time comparisons.

**references**
* [prenatal age terminology
](https://americanpregnancy.org/while-pregnant/fetal-development/)
* [ISO 8601 durations](https://en.wikipedia.org/wiki/ISO_8601#Durations)

**Comment by bendichter** [comment]
attn @satra @yarikoptic

**Comment by oruebel** [comment]
It sounds like ``age_type`` is really a form of reference time the age is relative to. If that is the case, I would recommend to use a more explicit name for the attribute, e.g., ``age_reference``. 

For backward compatibility the default_value should be ``birth`` so that we can autofill the value for older files that do not have the attribute. 

If I remember correctly you also created at some point an issue on being able to omit subject.age for HIPAA compliance. Since the ``age_type`` is an enumerated attribute with only a small set of allowed values, you could add a ``age_type=private`` (or something along those lines) to indicate that the age is restricted, private information.

**Comment by bendichter** [comment]
Yeah, we tossed around the idea of using age_reference as well. I was leaning towards that. For fetal, we could make age_reference "conception". Then I found that for gestational age, which is the more common way to express prenatal age, it's a bit more awkward to specify: time since the mother's last normal menstrual period. This is often abbreviated as LMP, but I wouldn't expect most neuroscientists to know that (though perhaps this is my male bias), so I think it would be confusing to have the age_reference be "LMP". To avoid confusion, I thought we might as well use the more common terms, fetal and gestational, instead of creating our own terminology. Ultimately, I think the best approach would be to see how other systems do it and copy them. Any ideas for where we might find how other systems specify this information?

**Comment by satra** [comment]
fyi: https://www.ebi.ac.uk/ols/ontologies/hsapdv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHsapDv_0000000&viewMode=All&siblings=false 

:)

**Comment by bendichter** [comment]
Thanks Satra. Sheesh, I guess that is what happens when you take a continuous variable and try to represent it categorically. Though there is some helpful terminology here. This source suggests that "post-fertilization" would be a better term than "conception."

**Comment by satra** [comment]
yes, could be IVF (very clear marker).
