### ISSUE TITLE
Follow semantic version (actually which one and what version?) for pre-releases

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/nwb-schema#427]
```yaml
  - name: nwb_version
    dtype: text
    value: 2.2.2
    doc: File version string. Use semantic versioning, e.g. 1.2.1. This will be the
      name of the format with trailing major, minor and patch numbers.
```

#422 is about to introduce `2.2.3a` version.  Apparently it is not a proper semantic version according to https://semver.org/ version 2 (if that is the versioning scheme used) where it is
```
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>

<version core> ::= <major> "." <minor> "." <patch>
...
```
That is why no semantic versioning modules can handle it:
```
$>  python -c "import semantic_version as sv; print(sv.__version__);sv.Version('2.2.3a')"
2.8.5.dev0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "semantic_version/base.py", line 105, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "semantic_version/base.py", line 311, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '2.2.3a'
```
```
$> python3 -c "import semver; semver.parse('2.2.3a')"           
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/semver.py", line 21, in parse
    raise ValueError('%s is not valid SemVer string' % version)
ValueError: 2.2.3a is not valid SemVer string
```
For prerelease it should be something like `2.2.3-a` or `2.2.3-alpha` etc. 

Note that pre-releases seems to be present in semver 2.0 but not in 1.0.

Description of the `nwb_version` should get adjusted to be more specific (e.g. point to semver.org, specify version), and then versions used should be verified (in a test)to be correctly specified (e.g. using `semver` or `semantic_version` modules)

Relates: #426

**Comment by rly** [comment]
I am in favor of following semantic versioning (v2.0) for pre-releases. I thought that is what we were doing, but apparently not. I just created a PR for our extensions versioning guidelines https://github.com/nwb-extensions/nwb-extensions.github.io/pull/11 . If @oruebel agrees, I will push that and also create a PR here to update the nwb-schema software process document (just added in #424) and update #422 accordingly.

Note that between NWB versions 2.0.0 and 2.1.0, in `nwb.file.yaml`, the NWB version was accidentally left as `'2.0b'` and so NWB files generated from PyNWB (and maybe also MatNWB) using NWB versions between 2.0.0 and 2.1.0 have attribute `/nwb_version` set to `'2.0b'`. So some older files do not follow semantic versioning.

> Note that pre-releases seems to be present in semver 2.0 but not in 1.0.

I see pre-releases already in [semver 1.0](https://semver.org/spec/v1.0.0.html), fourth bullet point.

**Comment by oruebel** [comment]
>  I thought that is what we were doing, but apparently not

That was the goal, but I guess some differences snuck in when I adapted the documents for our needs.

**Comment by stephprince** [comment]
The software process documentation was updated to use semantic versioning (v2.0) in https://github.com/NeurodataWithoutBorders/nwb-schema/pull/475.
