### ISSUE TITLE
Copy GH PR templates and software process from hdmf-common-schema

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#444]
https://github.com/hdmf-dev/hdmf-common-schema recently added PR templates to standardize and streamline PRs and release PRs. Those templates would be useful here as well.

https://hdmf-common-schema.readthedocs.io/en/latest/software_process.html also has the most recent iteration of the schema repo software process. The software process docs for nwb-schema should be reviewed and updated to be close to that of hdmf-common-schema.

**Comment by stephprince** [comment]
PR templates and an updated software process were added in https://github.com/NeurodataWithoutBorders/nwb-schema/pull/475.
