### ISSUE TITLE
file_create_date should not be changed to an attribute

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/nwb-schema#45]
I've implemented an API for Igor Pro [1] for reading and writing a NWB files. It implements our subset of the NWB specification language which we use.

In the course of implementing this API the dataset `file_create_date` was introduced and `modification_time` was deprecated due to my intervention.
See [2] for the changelog entry.

You now seem to partly undo that with the proposed NWB changes.

My original argumentation was:

```
The definition of modification_time as attribute is suboptimal.
* Attributes can only be read/written in full. This means I always have 
to read the whole array append to it and then write it back. This also 
means I can not just append to it as e.g. possible with datasets.
* Attributes should be smaller than 64kB, this can be worked around with 
some effort though [1]. This limit restricts the nwb files to fewer than 
~3000 modifications as my ISO8601 timestamps are 20 characters long.
Therefore I would propose to instead use the dataset 
"/modification_time". Datasets allow partial IO and don't have a size 
restriction. The attribute "modification_time" would only be allowed for 
backward compatibility.
```

In addition there are some limitations on how often you can overwrite an attribute [2]

So I would be in favour of keeping `file_create_date` as an dataset.

[1]: https://github.com/AllenInstitute/IPNWB
[2]: file:///home/firma/devel/nwb-schema/docs/format/_build/html/format.html#october-7th-2015
[2]: https://www.hdfgroup.org/HDF5/doc/UG/13_Attributes.html#SpecIssues
[3]: https://github.com/Unidata/netcdf-c/issues/350

**Comment by oruebel** [comment]
@t-b thanks for your feedback. If I understand correctly, you are referring to the description of proposed future changes here http://nwb-schema.readthedocs.io/en/latest/format.html#proposed-future-changes . Those changes have not been implemented yet and I think they'll most likely be part of the next iteration of changes. Actually, that particular section of the documentation should be removed or at least modified to point to corresponding issues on GitHub. I'll do the following to address this ticket:

1) I'll create a new issue for the proposed change in which I will include your reasoning for why file_create_date should not be made an attribute to make sure that i) when we plan the next round of changes that this is not lost and ii) to make sure we have a dedicated ticket to discuss those changes. 
2) I'll update the documentation to point to the issues that cover proposed future changes.

**Comment by oruebel** [comment]
I've added issue #48 to formally document the proposed changes in an issue and referenced this issue for details regarding ``file_create_date``. I've also update the documentation of proposed changes in the format docs to point to issues to avoid duplication and ease discussion of these issues.

**Comment by t-b** [comment]
> If I understand correctly, you are referring to the description of proposed future changes here http://nwb-schema.readthedocs.io/en/latest/format.html#proposed-future-changes .

Yes correct.

Thanks for dealing with this so quickly.
