### ISSUE TITLE
Where to add "screenshots"?

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/nwb-schema#451]
It seems that some labs (if not all) do a smart thing and take a screenshot of the acquisition console while commencing data collection. Such information is like a provenance record.  I wonder where in .nwb (or any extension?) would it be recommended to stick in such a list of screenshots which are not intended to be machine readable but a valuable metadata

**Comment by oruebel** [comment]
For this, I believe you would use:

- https://nwb-schema.readthedocs.io/en/latest/format.html#image to store a single image
- https://nwb-schema.readthedocs.io/en/latest/format.html#images to store a collection of images

**Comment by yarikoptic** [comment]
oh cool, there is a description in `images`, so indeed could stick them in there. if nwb widgets displays them - would be useful! thanks!

**Comment by bendichter** [comment]
@yarikoptic indeed they do
