### ISSUE TITLE
Signal decomposition

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#46]
Port of https://github.com/NeurodataWithoutBorders/pynwb/issues/9 to nwb-schema issue tracker.

A typical analysis is to perform a frequency decomposition (or other form of decomposition of signals), e.g,. of electrical recordings of the brain. This kind of analysis results in a timeseries with an additional dimension to represent the bands/features the signal is decomposed into. A possible target for this is FilteredEphys, but, e.g., the ElectricalSeries does only allow for 2D data.

**Comment by bendichter** [comment]
done. see `misc.DecompositionSeries`
