### ISSUE TITLE
Device model numbers

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#461]
Devices should allow for an optional model number field. Also, there is a general rule that devices can be specified by certain specs, or by a model number, which can be looked up. For instance, if a user wants to document an objective lens, they can specify it either by including the model number or by providing:
* manufacturer
* magnification
* aperture

Should be make this a general rule that device definitions have certain associated specs but these do not have to be supplied if a model number is given?

**Comment by rly** [comment]
Yes, definitely, we should add an optional `model_number` to `Device`. 

I think we should also add an optional `model_name` field. `model_name` would represent the consumer-facing description of the device and `model_number` represents the specific code or part number of the device within the manufacturer's inventory. `model_name` is useful if the `model_number` is cryptic. BUT perhaps users could just include this in the `description`. Users might also encode this in the `name`, but if you have, say, two different Neuropixels probes, the `name` for the probes cannot both be `'Neuropixels'`.

I think we should also add an optional `serial_number` field to `Device` to identify a globally unique instance of a device, given the model name/number and manufacturer. This is useful for tracking particular probes, microscopes, etc., within a lab. If I find out after data collection that a particular device is faulty, I want to know which data are impacted.

We could create a `Lens` subtype of `Device` that has `magnification` and `aperture` and say in its documentation that either `model_number` must be specified or {`manufacturer`, `magnification`, `aperture`} must be specified.

Related: https://github.com/NeurodataWithoutBorders/nwb-schema/issues/258
