### ISSUE TITLE
Add 'conversion_offset' option to ElectricalSeries

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-schema#465]
Hello,

I am looking to store raw acquisition trace data in a `uint16` form in an `ElectricalSeries`.

In the past, I have attached `int16` types with a corresponding `conversion` factor to translate the series into the proper units.

For `uint16` however, to take this approach and avoid having to store the data as a `float32` (after scaling into proper voltage units), we would need not only a `conversion` factor but also a `conversion_offset` amount to add after the scaling by the conversion factor.

Would this be possible to add to the schema for an `ElectricalSeries` in this case, or do you have any other suggestions?

**Comment by bendichter** [comment]
@rly what do you think?
