### ISSUE TITLE
Provide a field for orcID

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#477]
Experimenter names are not unique. When creating a database of NWB data, if there are two people with the same name who have generated data in the database, their data will be incorrectly linked to each other. orcID is a popular service that provides a unique ID for each researcher, and is used by many publications to uniquely identify an author.

DANDI shows orcIDs with their dandisets, but I believe these are human-entered. e.g., https://gui.dandiarchive.org/#/dandiset/000003

NWB should allow the inclusion of orcIDs for experimenters so that they can be uniquely identified. Right now the `/general/experimenters` dataset has shape (None, ) and dtype string. We could add orcIDs in:
1. an attribute on the `/general/experimenters` dataset with the same size as the dataset
2. a new dataset `/general/experimenter_orcids` with the same size as `/general/experimenters`
3. do nothing

**Comment by oruebel** [comment]
4. An alternative solution for ORCIDs would be to use ExternalResources. I think the mechanism for linking experimenter names to ORCID should essentially be the same as linking any other field to an ontology.

**Comment by rly** [comment]
That makes sense. Not sure why I didn't think of that!

**Comment by oruebel** [comment]
Closing this issue for now since this will be addressed by #1  and in [#15 in PyNWB](https://github.com/NeurodataWithoutBorders/pynwb/issues/15) and [HDMF ExternalResources](https://hdmf.readthedocs.io/en/stable/tutorials/External_Resources.html#sphx-glr-tutorials-external-resources-py)
