### ISSUE TITLE
Remove some required properties from the extracellular electrodes table

### ISSUE THREAD

**Issue by h-mayorquin** [NeurodataWithoutBorders/nwb-schema#505]
This is an issue resulting from the discussion between CatalystNeuro and the core nwb team today at 2022-04-22.
The idea is to reduce the number of required properties as `nwb-conversion-tools` in particular ends up filling them most of the time with default values. The underlying claim is that most of the time the information is not actually available so we are creating default data with not a strong purpose.

Right now the required properties are the following:
- x
- y
- z
- imp 
- location
-  filtering
-  group

The idea is the remove all of them save group.
If I understand correctly, when this works correctly we would add Quantity: 0 or 1 to most of the fields in the following of the schema:
https://nwb-schema.readthedocs.io/en/latest/format.html?highlight=electrodes#groups-general-extracellular-ephys-electrodes

**Comment by oruebel** [comment]
> If I understand correctly, when this works correctly we would add Quantity: 0 or 1 to most of the fields in the following of the schema:

correct


> The idea is the remove all of them save group.

* ``group`` should remain as required
* ``location``should remain as required
* ``x, y, z, imp, filtering`` become optional

**Comment by bendichter** [comment]
FYI, in the schema language, "0 or 1" is expressed by "?"
