### ISSUE TITLE
SpatialSeries data size constraints

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#509]
I just found a dataset on DANDI with a SpatialSeries that is shape n by 4. One of the columns is NaNs, so I think there is a mistake here. I would not have thought that would be possible, but when I looked at the shape constraints its 

```
((None,), (None, None))
```

I propose changing it to:

```
((None,), (None, 2), (None, 3))
```

**Comment by oruebel** [comment]
@bendichter that sounds reasonable to me

**Comment by rly** [comment]
I am in favor of this, though this is a breaking change. @bendichter could you survey all NWB files in DANDI and see if there are any SpatialSeries with different specs? There may be dandisets (e.g., from the allen institute) that stored data as Nx4 where the four columns are x1, y1, x2, y2.
