### ISSUE TITLE
schema validation

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/nwb-schema#52]
#6 & @t-b's questions has me thinking.

Is there currently a mechanism for validating one NWB file (or experiment dataset) against an arbitrary schema?

For example...

- If I have an NWB file that someone else has made w/ a custom extension, can I validate that it conforms to the NWB spec?
- One could imagine a schema change between 2.b and 2.a where only part of the schema changes, such that *some* 2.b files are 2.a compliant. For example, perhaps only ElectrodeGroup changes, such that files using ElectrodeGroup built on 2.b are not 2.a compliant but 2.b files that don't use ElectrodeGroup are 2.a compliant.
- as additional APIs are written (such as Matlab & IGOR), we'll need a way to validate compliance

**Comment by ajtritt** [comment]
The validitor is invoked like so:

```
$ python -m pynwb.validate
```

See the -p flag for validating against specs outside of the core specification
