### ISSUE TITLE
Add readthedocs.yaml

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#551]
From https://blog.readthedocs.com/migrate-configuration-v2/

> We are announcing a new requirement for all builds to use our configuration file version 2. This announcement deprecates builds without a configuration file, as well as version 1 of our configuration file.
> 
> Read the Docs will start requiring a .readthedocs.yaml configuration file for all projects in order to build documentation successfully. We will stop supporting builds without explicit configuration, because this creates implicit dependencies that users aren’t aware of. We plan to start failing builds not using configuration file version 2 on September 25, 2023.

We need to add a `.readthedocs.yaml` to all NWB and HDMF-related projects without one in the next two months. 

- [x] hdmf
- [x] hdmf-common-schema
- [x] hdmf-schema-language
- [x] NWB GUIDE
- [x] NWBInspector
- [x] nwb-overview
- [x] nwb-schema
- [ ] nwb-storage
- [x] PyNWB
- [x] schema-language

@mavaylon1 can you take care of these? Let me know if you have any permissions issues.

**Comment by mavaylon1** [comment]
I'll get on it.
