### ISSUE TITLE
Some broken links in the docs

### ISSUE THREAD

**Issue by VisLab** [NeurodataWithoutBorders/nwb-schema#553]
https://nwb-schema.readthedocs.io/en/latest/format_release_notes.html?highlight=Trial#improved-support-for-trial-based-data has some broken links... such as in:

> See the [PyNWB docs](https://pynwb.readthedocs.io/en/latest/tutorials/general/file.html?highlight=Trial#trials) for a short tutorial on how to use trials.

Thx

**Comment by oruebel** [comment]
Thanks for the issue note. For the PyNWB tutorial for trials you can see here: 

https://pynwb.readthedocs.io/en/stable/tutorials/general/plot_timeintervals.html#sphx-glr-tutorials-general-plot-timeintervals-py

**Comment by rly** [comment]
Closed by #562
