### ISSUE TITLE
Why is optical channel not a link in ImagingPlane?

### ISSUE THREAD

**Issue by ehennestad** [NeurodataWithoutBorders/nwb-schema#568]
Let's say I have a multichannel, multiplane (multiple depths) two-photon recording. For each `ImagingPlane` I would use the same optical channel but following the schema I need to add duplicated instances of the `OpticalChannel` to each imaging plane at different depths

**Comment by CodyCBakerPhD** [comment]
This is one of several things about the ophys schemas being improved in the [ndx-microscopy extension](https://github.com/catalystneuro/ndx-microscopy/issues/4) which is then planned to then be submitted to the TAB for approval to be integrated into the core here

**Comment by rly** [comment]
The [ndx-multichannel-volume extension](https://github.com/focolab/ndx-multichannel-volume) for multichannel multiplane imaging should also support this.

**Comment by ehennestad** [comment]
Thanks for clarifications!
