### ISSUE TITLE
Make `band_mean` and `band_sd` in `DecompositionSeries` optional

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-schema#570]
The docs for `band_mean` and `band_sd` in `DecompositionSeries` say that these fields are specific to Gaussian filters. Not all filters used in neurophysiology are Gaussian though, e.g., an LFP decomposition into alpha, beta, and gamma bands is not Gaussian, and LFP decomposition is supposed to be supported by this neurodata type. These table columns should be optional.

Relatedly, the `DecompositionSeries.bands` table should be its own type. See https://github.com/NeurodataWithoutBorders/nwb-schema/issues/336

**Comment by stephprince** [comment]
I came across this issue when trying to add a documentation example for `DecompositionSeries` to address https://github.com/NeurodataWithoutBorders/pynwb/issues/1938. I agree `band_mean` and `band_sd` should be made optional as they do not apply to all filter types. 

It might be helpful to add an optional `filter` or `filter_type` text column as the type of filter used is relevant information for interpreting the `DecompositionSeries` data values.

**Comment by rly** [comment]
I agree @stephprince
