### ISSUE TITLE
Update Required for NWB Format Documentation to Reflect Latest Release (2.7)

### ISSUE THREAD

**Issue by tabedzki** [NeurodataWithoutBorders/nwb-schema#579]
I've noticed that the current documentation for the [NWB Format Overview](https://nwb-schema.readthedocs.io/en/latest/format.html#type-specifications) appears to be outdated. It references version 2.6.0-alpha, while the latest release is version 2.7, which was made available in February. This discrepancy might be limited to versioning details within the documentation, but it could potentially lead to confusion or misalignment with the latest features and specifications of the NWB format.

Could the documentation be reviewed and updated to accurately reflect the features and versioning of the 2.7 release?

Thank you in advance for your help

**Comment by stephprince** [comment]
@tabedzki good catch - thanks for pointing that out!

It looks like the readthedocs project needed to be rebuilt. The docs should now be updated to reflect the [2.7.0 release](https://nwb-schema.readthedocs.io/en/stable/format.html). Let me know if you come across any remaining discrepancies.
