### ISSUE TITLE
Wrong version number for version attribute of NWB file in NWB Schema version 2.2.0

### ISSUE THREAD

**Issue by ehennestad** [NeurodataWithoutBorders/nwb-schema#589]
For the version 2.2.0 release of the nwb-schema the file version attribute in `nwb.file.yaml` is 2.1.0.

This is outdated now, but I am suspecting it is contributing to a whole class of different error messages when trying to open NWB Files in matnwb using `nwbRead` where the file is created with v2.2.0 but the nwb file version attribute is set to 2.1.0 due to this error in the schema.

I did a quick search in issues, but could not find any mention of this. Is this a known issue? If yes, please point me to discussions regarding this. If no, is there anything that can be done at this time? 

~~As the `hdmf_common` namespace was introduced with v2.2.0 this is potentially a critical bug for nwb files created in matnwb using v2.2.0.~~

Edit: Assuming the correct versions of the schemas are embedded in the file, I don't think the above statement is correct.

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/62c73400565afc28f67ede4f2e86023c33167cf8/core/nwb.file.yaml#L10

**Comment by stephprince** [comment]
Thanks for the issue @ehennestad.

@rly It looks like you had fixed the [version mismatch](https://github.com/NeurodataWithoutBorders/nwb-schema/issues/390) previously, do you remember if there was any discussion about this or could you advise?

**Comment by ehennestad** [comment]
Great, I see that this was fixed by bumping version up to 2.2.1 ~1week later, so maybe this was not really exposed to users for a long time
