### ISSUE TITLE
"manifold" in ImagingPlane

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/nwb-schema#59]
can someone please clarify what this required attribute is supposed to be?

```
manifold (Iterable): Physical position of each pixel. height, weight, x, y, z.
```

is this supposed to be a 5 x n_pixels array?

what is the ordering of the pixels?

**Comment by ajtritt** [comment]
This was carried over from the original schema. @jeffteeters do you know what this is field represents?

**Comment by jeffteeters** [comment]
I did not create this, but according to the description in the v1.0.6 schema, "manifold" is a recommended dataset associated with each
    "/general/optophysiology/<imaging_plane_X>/"
it is meant to contain: "Physical position of each pixel. "xyz" represents the position of the pixel relative to the defined coordinate space".  I think there is an error in the schema, "weight" should be "width".

The contents are a dataset of type float32 with dimensions: ["height", "width", "xyz"].  I think "height" and "width" are the index to the pixel in the imaging plane.   "xyz" indicates three elements (float32) specifying the x, y and z location of the pixel.

For example, if there was a 400x600 imaging plane, dataset would have dimensions
400 x 600 x 3,  and elements [0,0,0], [0,0,1] and [0,0,2] would respectively store the "x", "y" and "z" location of the first pixel and [399,599,0],  [399,599,1],  [399,599,2] would respectively store the "x", "y" and "z" locations for the last pixel.

It the v1.0.6 schema, "manifold" has an accompanying dataset, "reference_frame" which "is necessary to interpret manifold".  It is described as:
"Describes position and reference frame of manifold based on position of first element in manifold. For example, text description of anatomical location or vectors needed to rotate to common anatomical axis (eg, AP/DV/ML)."

(Note: In the 1.0.6 schema, the above description had a misspelling, "anotomical" should be "anatomical").

**Comment by neuromusic** [comment]
Thank you for the clarification @jeffteeters :) That makes more sense... I hope we can get that information baked into the documentation here a bit better.

In the schema defined here, manifold is *required* but in v1.0.6 you say it is *recommended*.

While this is clearly useful information if it is available, it strikes me as a burdensome to include as a requirement. For example, none of the released Allen Institute Brain Observatory NWB files use this attribute, so as long as this is required, we cannot conform to the new schema. (cc @nicain)

Are there other "recommended" attributes that the new schema has re-classified as "required"?

**Comment by ajtritt** [comment]
Any field that was not required in 1.0.6 should not be required in 2.0. It looks like this _manifold_ went from required to recommended between 1.0.5 and 1.0.6, and I believe we did the restructuring for 2.0  starting from 1.0.4. I'll create an issue to ensure that changes between 1.0.4 and 1.0.6 make it through.

**Comment by ajtritt** [comment]
addressed by #63

**Comment by neuromusic** [comment]
fantastic. thanks @ajtritt!!

**Comment by bendichter** [comment]
I also found this very confusing when I came across it in the docs. Thanks @jeffteeters for clearing it up. I'm going to re-open this because I think it requires changes to the documentation so that this information is clear from the schema file.

One additional question I have is how would we deal with volumetric data? The natural extension of the current setup would be [width, heigh, depth, xyz]. If that's the way we want to go, we should add it to the documentation.

**Comment by ajtritt** [comment]
We should also change the shape of this dataset. Based on what @jeffteeters said, the shape of this dataset should be (None, None, 3) then. The first two None’s correspond to no restrictions for “height” and “width”, and 3 in the third dimension for x, y, and z.

**Comment by jonc125** [comment]
Support for volumetric data as @bendichter says would be useful for #156. Should adding a depth dimension be optional, or for the 2d case can it just have length 1?

**Comment by oruebel** [comment]
See https://github.com/NeurodataWithoutBorders/pynwb/pull/576
