### ISSUE TITLE
ease provenance-tracking requirements for dF/F

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/nwb-schema#61]
Saving fluorescence traces is one of the fundamental use-cases for calcium imaging experiments, however, the nwb-schema places a significant burden on users trying to save this type of data. 

For example, here is the pynwb code I needed to define dF/F traces for a single experiment.
https://gist.github.com/neuromusic/b44fa185f03b7e588af7f5e7ccb52bdd

In the above example, I have one primary array of data that is relevant.
- an array of dF/F traces (dimensions: neurons * time)

The NWB object that is meant (according to its description) to define dF/F traces is "DfOverF" in the ophys module:
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.ophys.yaml#L65

This object has two attributes: "name" and "roi_response_series"... it maintains no data on its own, rather it is a simple wrapper for "RoiResponseSeries", which is where the data is stored:
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.ophys.yaml#L33

There are two problems with RoiResponseSeries.

First, it is impossible to simply save this object into an NWB file. It is not raw, so it is not "allowed" in `/acquisition`, instead a processing module must be defined to contain it. The inability to store derived data without specifying a processing module is a general concern with the NWB schema that I'm not going to address here. 

The second issue is that I cannot define the RoiResponseSeries without first defining a `segmenttation_interface` (sic, see https://github.com/NeurodataWithoutBorders/pynwb/issues/126) of type ImageSegmentation, which itself is nothing more than a name and source and pointer to a PlaneSegmentation.

In turn, I cannot define a Plane Segmentation without giving it (a) a list of ROI objects, (b) an ImagingPlane, and (c) an ImageSeries for `reference_images`.

Further, the ImagingPlane needs an OpticalChannel and each ROI needs an ImageSeries for `reference_images` as well.

To visualize this chain of requirements...

- DfOverF
  - roi_response_series (RoiResponseSeries)
    - segmentation_interface (ImageSegmentation)
      - plane_segmentation (PlaneSegmentation)
        - reference_images (ImageSeries)
        - imaging_plane (ImagingPlane)
          - channel (OpticalChannel)
        - roi_list 
          - (ROI)[0]
            - reference_images (ImageSeries)
          - (ROI)[1]
            - reference_images (ImageSeries)
          - ...
          - (ROI)[n]
            - reference_images (ImageSeries)

Even including the additional data that is stored in this hierarchy, we are are only talking about three arrays of data:
- an array of dF/F traces (dimensions: neurons * time)
- an array of ROI masks (dimensions: neurons * field_of_view_x * field_of_view_y)
- an array that displays the max projection of the full calcium timeseries, for a compact reference to visualize the ROIs (dimensions: field_of_view_x * field_of_view_y)

These three arrays get saved in 7+n classes, where 'n' is the number of neurons/ROIs that the experimenter wishes to save, each with it's own set of required fields. In my own example above, this took ~ 100 lines of code.

This is a rather burdensome set of requirements on the lowly experimenter to save such common data. 

At the core of these set of objects are the traces (stored in the RoiResponseSeries) & their provenance (stored in the PlaneSegmentation). I think that the burden could be eased significantly with one key backward-compatible change:
- Remove the requirement for calcium traces to record their full provenance. This can be achieved by making the "segmentation_interface" attribute of RoiResponseSeries optional.

This change would still permit users to save provenance information if they wish, while easing the requirements for those who don't need to share this information.

In the future (perhaps for NWB 3.0?) a more comprehensive refactoring can be considered that would simplify the segmentation side of this data.

**Comment by nicain** [comment]
> Remove the requirement for calcium traces to record their full provenance. This can be achieved by making the "segmentation_interface" attribute of RoiResponseSeries optional.

@neuromusic Is this functionally equivalent (or actually equivalent) to @lfrank 's suggestion from the Slack developers #general channel:

> Agreed.  I could imagine that just making the other arguments optional would help, but I’m not sure this is a good solution from the developer perspective.  Nicholas or Justin - have you submitted an issue on this?

?

**Comment by neuromusic** [comment]
@nicain functionally, yes. by making the segmentation_interface optional, everything else becomes optional w/r/t the RoiResponseSeries. In my proposal above, you don't get to pick and choose which pieces you want... once you decide you want to save ROIs, you need to define a segmentation_interface and define the all of the dependent relationships.

Somewhat redundantly, RoiResponseSeries maintains a required attribute called `roi_name` which is an iterable with just the names of the ROIs. It's not clear, but I think that this is supposed to line up with the "name" attribute on each of the ROI groups. Despite the extensive architecture here to track the different pieces of the segmentation, there's really nothing else here to line up the index of the trace with the ROI group, so this fundamental relationship between the traces and the ROIs is left without an explicit relationship in the schema. That's the trouble with maintaining provenance relationships in a hierarchical structure though, I guess.

It seems to me that the issue here is that the data architecture has "segmentation" in between the traces and the ROIs...

```
dF/F  <->  segmentation  <->  ROIs
```

A cleaner architecture that we could consider for NWB 3.0 would include a NetCDF/xarray style Dimension Scales on the fluorescence traces to directly annotate ROI names that would then index into an ROITable (in a similar way that the new ElectrodeTable works), then maintain the segmentation information in another object that describes the imaging planes, etc.

```
dF/F  <->  ROIs  <->  segmentation
```

Without going down the Dimension Scales route, it might be possible to replace roi_names with roi_list, which would give us a schema like...

- DfOverF
  - roi_response_series (RoiResponseSeries)
    - roi_list
      - (ROI)[0]
        - reference_images (ImageSeries)
      - (ROI)[1]
        - reference_images (ImageSeries)
      - ...
      - (ROI)[n]
        - reference_images (ImageSeries)
- plane_segmentation (PlaneSegmentation)
  - reference_images (ImageSeries)
  - imaging_plane (ImagingPlane)
  - channel (OpticalChannel)
  - roi_list

where both the PlaneSegmentation and RoiResponseSeries reference the ROIs themselves.

I haven't thought much about the risks of such an approach, though... switching one reference from "required" to "optional" seems safer :P
