### ISSUE TITLE
Make sure relevant changes between NWB 1.0.4 and 1.0.6 make it to 2.0

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/nwb-schema#63]
The reformatting of the spec document to NWB 2.0 started from the 1.0.4 schema, so changes to the 1.x schema did not make it through 

We need to check to ensure the following versions' changes made it are relevant and if so, made it into 2.0
- [ ] 1.0.5_beta
- [ ] 1.0.5a_beta
- [ ] 1.0.5b_beta
- [ ] 1.0.5c_beta
- [ ] 1.0.5d_beta
- [ ] 1.0.5e_beta
- [ ] 1.0.5f_beta
- [ ] 1.0.5g_beta
- [ ] 1.0.5h_beta
- [ ] 1.0.5i_beta
- [ ] 1.0.6

**Comment by oruebel** [comment]
The release notes with the list of changes from those versions are both in the original docs https://github.com/NeurodataWithoutBorders/specification/tree/master/version_1.0.6 as well as the release notes of the current docs. I don't know if those release notes are complete but I think Jeff is usually pretty thorough with those things.
