### ISSUE TITLE
Build ePub docs for docs/format on ReadTheDocs

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#67]
Due to the 900s time limit for builds on ReadTheDocs we had to disable the build of ePub for the format specification docs only (i.e., ```docs/format```), i.e., currently only PDF and HTML are being built automatically on ReadTheDocs for the format docs. 

We recently integrated the generation of the Sphinx sources from the YAML spec with the automatic build of the docs on ReadTheDocs. This change was made to ensure that the docs stay in sync with the spec. However, already before this was included, the build times on ReadTheDocs were often >800s and with the addition of the doc generation this led to the build often exceeding the time limit. I did add logic to ensure that the generation of the sources is only run once during each build by storing the git hash for the files in the output folder and regenerating the files only if the githash is out-of-date. This reduces the build time significantly but was often still not enough. To allow ReadTheDocs to build within the time limit I, therefore, disabled the ePub build which seems to save enough time to make things work correctly. If we really need ePub then we might need to consider getting a subscription for ReadTheDocs to increase build time limits.

**Comment by neuromusic** [comment]
how important is the ePub format?

**Comment by oruebel** [comment]
I mainly created the ticket to a) document the issue and b) as a reminder so that I can look at it again some other time, but don't view this as a major issue.  In particular I think it is more important to have the format docs be consistent with the YAML spec (rather than someone having to rerun the scripts manually every time the spec changes, do a pull request etc.). Also, not having to manage all those binary PDF and PNG files in the Git repo is nice too.   Because of this, I figured not building ePub was an acceptable sacrifice to make that 99% of people probably won't care about and as long as we have HTML and PDF versions I think we are fine. Ultimately the solution is simple, if we really want ePub then we'll need to find someone to pay for a subscription on RTD and then have RTD bump up the build time limit a bit.

**Comment by neuromusic** [comment]
> I figured not building ePub was an acceptable sacrifice to make that 99% of people probably won't care about and as long as we have HTML and PDF versions I think we are fine. 

agreed 100%.

**Comment by neuromusic** [comment]
and if it reduces your cognitive overhead, I'm OK with closing this issue until someone asks for epub documentation

**Comment by oruebel** [comment]
This is a non-critical issue. Closing it for now. We can reopen it if it becomes important in the future.
