### ISSUE TITLE
Require Timestamps in SpikeEventSeries

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/nwb-schema#7]
Originally reported by: **Loren Frank (Bitbucket: [lmfrnk](https://bitbucket.org/lmfrnk), GitHub: Unknown)**

----------------------------------------

Right now timestamps are optional for a SpikeEventSeries.  The list of timestamps should be a required argument, as otherwise the times for each spike could get lost.

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/nwb-schema/issue/7

**Comment by ajtritt** [comment]
*Original comment by* **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**:

----------------------------------------

Issue #8 was marked as a duplicate of this issue.

**Comment by ajtritt** [comment]
*Original comment by* **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**:

----------------------------------------

PyNWB enforces this now. Still need to change in the schema

**Comment by oruebel** [comment]
@ajtritt can this issue be closed?
