### ISSUE TITLE
Is running speed in the schema?

### ISSUE THREAD

**Issue by dyf** [NeurodataWithoutBorders/nwb-schema#97]
I was running through @nicain 's notebook here:

https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/notebooks/read-Allen-Brain-Oservatory.ipynb

Running speed is being read out as "BehavioralTimeSeries".  Is there a RunningSpeed subclass needed here?

**Comment by neuromusic** [comment]
No. I consulted with @nicain on this...

The name of the *container* is BehavioralTimeSeries. It holds the time series object, which is named (by the user) "running_speed" & can be accessed in that example with `ts.name`

I don't see a reason to enforce a new RunningSpeed class in the schema

**Comment by dyf** [comment]
Sounds great.  Should df/f be handled the same way, then?

https://nwb-schema.readthedocs.io/en/latest/format.html#dfoverf

**Comment by neuromusic** [comment]
IMHO, yes, but it's harder to subtract from the schema :P

**Comment by dyf** [comment]
Okay.  Closing this issue, but if we're talking about taking API-breaking changes, I recommend standardizing the design by removing things like the DfOverF class.

**Comment by neuromusic** [comment]
I agree 100%. I'm not sure how schema decisions will get made, but I've got a bunch of open issues here on my suggested schema changes. Might as well add it to the list.
