### ISSUE TITLE
add description to this repo

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/nwb-schema#98]
can we add a description to this repo so it's purpose is clear from the repo listing & pinned repos?
https://github.com/NeurodataWithoutBorders

this also might be a good opportunity to update the README?

**Comment by jcfr** [comment]
Text could be `A schema definition for storing neurodata in HDF5 format.`

![screenshot from 2018-01-20 14-29-36](https://user-images.githubusercontent.com/219043/35187229-7bb19b66-fdee-11e7-94ef-2ed0f94d032e.png)

**Comment by neuromusic** [comment]
assigned to @oruebel since I don't have permissions on the repo to do this.

**Comment by jcfr** [comment]
Thanks @oruebel
