### ISSUE TITLE
proposal: remove DfOverF class

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/nwb-schema#99]
This class is little more than a semantic wrapper for RoiResponseSeries.

We should remove it in favor of the user creating an RoiResponseSeries which they name "df_over_f" or whatever they want to name it.

See the conversation on #97 regarding RunningSpeed.

cc @dyf

**Comment by nicain** [comment]
Closing this issue; it is preferable to not encode necessary semantic information in the name of the RoiResponseSeries
